import type { InstrumentCategory, InstrumentRelationType, InstrumentUniverseItem } from "./types";

const fullCoverage = {
  price: true,
  technical: true,
  fundamentals: true,
  fixedIncome: false,
  news: true,
};

const fixedIncomeCoverage = {
  price: true,
  technical: true,
  fundamentals: false,
  fixedIncome: true,
  news: true,
};

const futureCoverage = {
  price: false,
  technical: false,
  fundamentals: false,
  fixedIncome: false,
  news: false,
};

function bondItem(input: {
  symbol: string;
  displayName: string;
  displayNameEs?: string;
  category: InstrumentCategory;
  currency: string;
  quoteCurrency: string;
  settlementContext: string;
  settlementContextEn: string;
  settlementContextEs: string;
  indexationType?: string;
  marketConventionLabelEn: string;
  marketConventionLabelEs: string;
  primarySymbol: string;
  relatedSymbols: string[];
  relationType: InstrumentRelationType;
  isPrimary: boolean;
  priority: number;
}) {
  return {
    ...input,
    country: "AR" as const,
    market: "BYMA" as const,
    localTicker: input.symbol,
    underlyingSymbol: input.primarySymbol,
    displayCurrency: input.currency,
    quoteCurrency: input.quoteCurrency,
    tradingCurrency: input.currency,
    settlementCurrency: input.quoteCurrency,
    settlementContext: input.settlementContext,
    settlementContextEn: input.settlementContextEn,
    settlementContextEs: input.settlementContextEs,
    indexationType: input.indexationType,
    marketConventionLabel: input.marketConventionLabelEn,
    marketConventionLabelEn: input.marketConventionLabelEn,
    marketConventionLabelEs: input.marketConventionLabelEs,
    sourceStatus: "mock_supported" as const,
    dataCoverage: fixedIncomeCoverage,
    isSearchable: true,
    tags: ["argentina", "fixed income", "bond", "species", "mock"],
    searchableAliases: [input.primarySymbol, ...input.relatedSymbols],
  };
}

function equityItem(symbol: string, displayName: string, sector: string, priority: number): InstrumentUniverseItem {
  return {
    symbol,
    displayName,
    category: "equity",
    country: "AR",
    market: "BYMA",
    currency: "ARS",
    localTicker: symbol,
    displayCurrency: "ARS",
    tradingCurrency: "ARS",
    settlementCurrency: "ARS",
    sector,
    primarySymbol: symbol,
    underlyingSymbol: symbol,
    relatedSymbols: [symbol],
    isPrimary: true,
    isSearchable: true,
    sourceStatus: symbol === "GGAL" || symbol === "YPFD" ? "mock_supported" : "future_supported",
    dataCoverage: symbol === "GGAL" || symbol === "YPFD" ? fullCoverage : futureCoverage,
    searchableAliases: [symbol, displayName, "merval", "accion argentina", "argentine equity"],
    tags: ["argentina", "equity", "merval", sector.toLowerCase()],
    priority,
  };
}

function cedearItem(symbol: string, displayName: string, sector: string, priority: number): InstrumentUniverseItem {
  return {
    symbol,
    displayName,
    displayNameEn: `${displayName} CEDEAR reference`,
    displayNameEs: `${displayName} - Referencia CEDEAR`,
    category: "cedear",
    country: "AR",
    market: "BYMA",
    currency: "ARS",
    localTicker: symbol,
    globalTicker: symbol,
    displayCurrency: "ARS",
    tradingCurrency: "ARS",
    settlementCurrency: "ARS",
    sector,
    primarySymbol: symbol,
    underlyingSymbol: symbol,
    underlyingName: displayName,
    relatedSymbols: [symbol],
    relationType: "cedear",
    isPrimary: true,
    isSearchable: true,
    sourceStatus: "mock_supported",
    dataCoverage: {
      price: true,
      technical: true,
      fundamentals: true,
      fixedIncome: false,
      news: false,
    },
    searchableAliases: [`${symbol} CEDEAR`, `${symbol} US stock`, `${symbol} local Argentine exposure`],
    tags: ["argentina", "cedear", "mock local price", "implied ccl", sector.toLowerCase()],
    priority,
    descriptionEn: "Provider underlying / mock local CEDEAR context for implied CCL analysis.",
    descriptionEs: "Subyacente proveedor / CEDEAR local simulado para análisis de CCL implícito.",
  };
}

export const ARGENTINA_INSTRUMENT_UNIVERSE: InstrumentUniverseItem[] = [
  bondItem({
    symbol: "AL30",
    displayName: "Bonar 2030",
    category: "sovereign_bond",
    currency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "Pesos",
    settlementContextEn: "Pesos",
    settlementContextEs: "Pesos",
    marketConventionLabelEn: "Peso trading species",
    marketConventionLabelEs: "Especie en pesos",
    primarySymbol: "AL30",
    relatedSymbols: ["AL30", "AL30D", "AL30C"],
    relationType: "peso_species",
    isPrimary: true,
    priority: 10,
  }),
  bondItem({
    symbol: "AL30D",
    displayName: "Bonar 2030 - Dollar MEP species",
    displayNameEs: "Bonar 2030 - Especie dólar MEP",
    category: "sovereign_bond",
    currency: "USD",
    quoteCurrency: "USD",
    settlementContext: "Dollar MEP",
    settlementContextEn: "Dollar MEP",
    settlementContextEs: "Dólar MEP",
    marketConventionLabelEn: "Dollar MEP species",
    marketConventionLabelEs: "Especie dólar MEP",
    primarySymbol: "AL30",
    relatedSymbols: ["AL30", "AL30D", "AL30C"],
    relationType: "dollar_mep_species",
    isPrimary: false,
    priority: 9,
  }),
  bondItem({
    symbol: "AL30C",
    displayName: "Bonar 2030 - Dollar cable/CCL species",
    displayNameEs: "Bonar 2030 - Especie dólar cable/CCL",
    category: "sovereign_bond",
    currency: "USD",
    quoteCurrency: "USD",
    settlementContext: "Dollar cable/CCL",
    settlementContextEn: "Dollar cable/CCL",
    settlementContextEs: "Dólar cable/CCL",
    marketConventionLabelEn: "Dollar cable/CCL species",
    marketConventionLabelEs: "Especie dólar cable/CCL",
    primarySymbol: "AL30",
    relatedSymbols: ["AL30", "AL30D", "AL30C"],
    relationType: "dollar_cable_species",
    isPrimary: false,
    priority: 8,
  }),
  bondItem({
    symbol: "GD30",
    displayName: "Global 2030",
    category: "global_bond",
    currency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "Pesos",
    settlementContextEn: "Pesos",
    settlementContextEs: "Pesos",
    marketConventionLabelEn: "Peso trading species",
    marketConventionLabelEs: "Especie en pesos",
    primarySymbol: "GD30",
    relatedSymbols: ["GD30", "GD30D", "GD30C"],
    relationType: "peso_species",
    isPrimary: true,
    priority: 10,
  }),
  bondItem({
    symbol: "GD30D",
    displayName: "Global 2030 - Dollar MEP species",
    displayNameEs: "Global 2030 - Especie dólar MEP",
    category: "global_bond",
    currency: "USD",
    quoteCurrency: "USD",
    settlementContext: "Dollar MEP",
    settlementContextEn: "Dollar MEP",
    settlementContextEs: "Dólar MEP",
    marketConventionLabelEn: "Dollar MEP species",
    marketConventionLabelEs: "Especie dólar MEP",
    primarySymbol: "GD30",
    relatedSymbols: ["GD30", "GD30D", "GD30C"],
    relationType: "dollar_mep_species",
    isPrimary: false,
    priority: 9,
  }),
  bondItem({
    symbol: "GD30C",
    displayName: "Global 2030 - Dollar cable/CCL species",
    displayNameEs: "Global 2030 - Especie dólar cable/CCL",
    category: "global_bond",
    currency: "USD",
    quoteCurrency: "USD",
    settlementContext: "Dollar cable/CCL",
    settlementContextEn: "Dollar cable/CCL",
    settlementContextEs: "Dólar cable/CCL",
    marketConventionLabelEn: "Dollar cable/CCL species",
    marketConventionLabelEs: "Especie dólar cable/CCL",
    primarySymbol: "GD30",
    relatedSymbols: ["GD30", "GD30D", "GD30C"],
    relationType: "dollar_cable_species",
    isPrimary: false,
    priority: 8,
  }),
  bondItem({
    symbol: "TX26",
    displayName: "CER-linked Argentine Treasury bond",
    displayNameEs: "Bono del Tesoro argentino ajustado por CER",
    category: "cer_bond",
    currency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "CER-linked / ARS",
    settlementContextEn: "CER-linked / ARS",
    settlementContextEs: "Pesos ajustados por CER",
    indexationType: "CER",
    marketConventionLabelEn: "CER-linked ARS bond",
    marketConventionLabelEs: "Bono CER",
    primarySymbol: "TX26",
    relatedSymbols: ["TX26"],
    relationType: "same_underlying",
    isPrimary: true,
    priority: 7,
  }),
  bondItem({
    symbol: "AE38",
    displayName: "Bonar 2038",
    category: "sovereign_bond",
    currency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "Pesos",
    settlementContextEn: "Pesos",
    settlementContextEs: "Pesos",
    marketConventionLabelEn: "Peso trading species",
    marketConventionLabelEs: "Especie en pesos",
    primarySymbol: "AE38",
    relatedSymbols: ["AE38", "AE38D"],
    relationType: "peso_species",
    isPrimary: true,
    priority: 6,
  }),
  bondItem({
    symbol: "AE38D",
    displayName: "Bonar 2038 - Dollar MEP species",
    displayNameEs: "Bonar 2038 - Especie dolar MEP",
    category: "sovereign_bond",
    currency: "USD",
    quoteCurrency: "USD",
    settlementContext: "Dollar MEP",
    settlementContextEn: "Dollar MEP",
    settlementContextEs: "Dolar MEP",
    marketConventionLabelEn: "Dollar MEP species",
    marketConventionLabelEs: "Especie dolar MEP",
    primarySymbol: "AE38",
    relatedSymbols: ["AE38", "AE38D"],
    relationType: "dollar_mep_species",
    isPrimary: false,
    priority: 5,
  }),
  bondItem({
    symbol: "GD35",
    displayName: "Global 2035",
    category: "global_bond",
    currency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "Pesos",
    settlementContextEn: "Pesos",
    settlementContextEs: "Pesos",
    marketConventionLabelEn: "Peso trading species",
    marketConventionLabelEs: "Especie en pesos",
    primarySymbol: "GD35",
    relatedSymbols: ["GD35", "GD35D"],
    relationType: "peso_species",
    isPrimary: true,
    priority: 6,
  }),
  bondItem({
    symbol: "GD35D",
    displayName: "Global 2035 - Dollar MEP species",
    displayNameEs: "Global 2035 - Especie dolar MEP",
    category: "global_bond",
    currency: "USD",
    quoteCurrency: "USD",
    settlementContext: "Dollar MEP",
    settlementContextEn: "Dollar MEP",
    settlementContextEs: "Dolar MEP",
    marketConventionLabelEn: "Dollar MEP species",
    marketConventionLabelEs: "Especie dolar MEP",
    primarySymbol: "GD35",
    relatedSymbols: ["GD35", "GD35D"],
    relationType: "dollar_mep_species",
    isPrimary: false,
    priority: 5,
  }),
  bondItem({
    symbol: "GD38",
    displayName: "Global 2038",
    category: "global_bond",
    currency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "Pesos",
    settlementContextEn: "Pesos",
    settlementContextEs: "Pesos",
    marketConventionLabelEn: "Peso trading species",
    marketConventionLabelEs: "Especie en pesos",
    primarySymbol: "GD38",
    relatedSymbols: ["GD38", "GD38D"],
    relationType: "peso_species",
    isPrimary: true,
    priority: 6,
  }),
  bondItem({
    symbol: "GD38D",
    displayName: "Global 2038 - Dollar MEP species",
    displayNameEs: "Global 2038 - Especie dolar MEP",
    category: "global_bond",
    currency: "USD",
    quoteCurrency: "USD",
    settlementContext: "Dollar MEP",
    settlementContextEn: "Dollar MEP",
    settlementContextEs: "Dolar MEP",
    marketConventionLabelEn: "Dollar MEP species",
    marketConventionLabelEs: "Especie dolar MEP",
    primarySymbol: "GD38",
    relatedSymbols: ["GD38", "GD38D"],
    relationType: "dollar_mep_species",
    isPrimary: false,
    priority: 5,
  }),
  bondItem({
    symbol: "AL35",
    displayName: "Bonar 2035",
    category: "sovereign_bond",
    currency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "Pesos",
    settlementContextEn: "Pesos",
    settlementContextEs: "Pesos",
    marketConventionLabelEn: "Peso trading species",
    marketConventionLabelEs: "Especie en pesos",
    primarySymbol: "AL35",
    relatedSymbols: ["AL35", "AL35D"],
    relationType: "peso_species",
    isPrimary: true,
    priority: 6,
  }),
  bondItem({
    symbol: "AL35D",
    displayName: "Bonar 2035 - Dollar MEP species",
    displayNameEs: "Bonar 2035 - Especie dolar MEP",
    category: "sovereign_bond",
    currency: "USD",
    quoteCurrency: "USD",
    settlementContext: "Dollar MEP",
    settlementContextEn: "Dollar MEP",
    settlementContextEs: "Dolar MEP",
    marketConventionLabelEn: "Dollar MEP species",
    marketConventionLabelEs: "Especie dolar MEP",
    primarySymbol: "AL35",
    relatedSymbols: ["AL35", "AL35D"],
    relationType: "dollar_mep_species",
    isPrimary: false,
    priority: 5,
  }),
  bondItem({
    symbol: "TZX26",
    displayName: "CER-linked Treasury bond TZX26",
    displayNameEs: "Bono del Tesoro TZX26 ajustado por CER",
    category: "cer_bond",
    currency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "CER-linked / ARS",
    settlementContextEn: "CER-linked / ARS",
    settlementContextEs: "Pesos ajustados por CER",
    indexationType: "CER",
    marketConventionLabelEn: "CER-linked ARS bond",
    marketConventionLabelEs: "Bono CER",
    primarySymbol: "TZX26",
    relatedSymbols: ["TZX26"],
    relationType: "same_underlying",
    isPrimary: true,
    priority: 5,
  }),
  bondItem({
    symbol: "DICP",
    displayName: "Discount bond in pesos",
    displayNameEs: "Bono Discount en pesos",
    category: "cer_bond",
    currency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "CER-linked / ARS",
    settlementContextEn: "CER-linked / ARS",
    settlementContextEs: "Pesos ajustados por CER",
    indexationType: "CER",
    marketConventionLabelEn: "CER-linked ARS bond",
    marketConventionLabelEs: "Bono CER",
    primarySymbol: "DICP",
    relatedSymbols: ["DICP"],
    relationType: "same_underlying",
    isPrimary: true,
    priority: 4,
  }),
  bondItem({
    symbol: "PARP",
    displayName: "Par bond in pesos",
    displayNameEs: "Bono Par en pesos",
    category: "cer_bond",
    currency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "CER-linked / ARS",
    settlementContextEn: "CER-linked / ARS",
    settlementContextEs: "Pesos ajustados por CER",
    indexationType: "CER",
    marketConventionLabelEn: "CER-linked ARS bond",
    marketConventionLabelEs: "Bono CER",
    primarySymbol: "PARP",
    relatedSymbols: ["PARP"],
    relationType: "same_underlying",
    isPrimary: true,
    priority: 4,
  }),
  bondItem({
    symbol: "S31Y6",
    displayName: "LECAP sample S31Y6",
    displayNameEs: "LECAP de ejemplo S31Y6",
    category: "lecap",
    currency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "ARS treasury bill",
    settlementContextEn: "ARS treasury bill",
    settlementContextEs: "Letra capitalizable en pesos",
    marketConventionLabelEn: "ARS LECAP",
    marketConventionLabelEs: "LECAP en pesos",
    primarySymbol: "S31Y6",
    relatedSymbols: ["S31Y6"],
    relationType: "same_underlying",
    isPrimary: true,
    priority: 4,
  }),
  equityItem("GGAL", "Grupo Financiero Galicia", "Financials", 7),
  equityItem("YPFD", "YPF Sociedad Anonima", "Energy", 7),
  equityItem("PAMP", "Pampa Energia", "Energy", 4),
  equityItem("TXAR", "Ternium Argentina", "Materials", 3),
  equityItem("ALUA", "Aluar Aluminio Argentino", "Materials", 3),
  equityItem("TGSU2", "Transportadora de Gas del Sur", "Utilities", 3),
  equityItem("CEPU", "Central Puerto", "Utilities", 3),
  equityItem("COME", "Sociedad Comercial del Plata", "Industrials", 3),
  equityItem("BYMA", "Bolsas y Mercados Argentinos", "Financials", 3),
  equityItem("SUPV", "Grupo Supervielle", "Financials", 3),
  equityItem("VALO", "Banco de Valores", "Financials", 3),
  equityItem("BBAR", "Banco BBVA Argentina", "Financials", 3),
  equityItem("BMA", "Banco Macro", "Financials", 4),
  equityItem("EDN", "Edenor", "Utilities", 3),
  equityItem("TRAN", "Transener", "Utilities", 3),
  equityItem("TGNO4", "Transportadora de Gas del Norte", "Utilities", 3),
  equityItem("MIRG", "Mirgor", "Technology", 3),
  equityItem("LOMA", "Loma Negra", "Materials", 3),
  equityItem("CRES", "Cresud", "Real Estate", 3),
  equityItem("IRSA", "IRSA", "Real Estate", 3),
  equityItem("METR", "Metrogas", "Utilities", 2),
  equityItem("AGRO", "Agrometal", "Industrials", 2),
  equityItem("HARG", "Holcim Argentina", "Materials", 2),
  equityItem("TECO2", "Telecom Argentina", "Communication Services", 2),
  equityItem("MOLI", "Molinos Rio de la Plata", "Consumer Staples", 2),
  cedearItem("AAPL", "Apple CEDEAR reference", "Technology", 5),
  cedearItem("MSFT", "Microsoft CEDEAR reference", "Technology", 4),
  cedearItem("NVDA", "NVIDIA CEDEAR reference", "Technology", 4),
  cedearItem("TSLA", "Tesla CEDEAR reference", "Consumer Discretionary", 4),
  cedearItem("AMZN", "Amazon CEDEAR reference", "Consumer Discretionary", 4),
  cedearItem("META", "Meta CEDEAR reference", "Communication Services", 4),
  cedearItem("GOOGL", "Alphabet CEDEAR reference", "Communication Services", 4),
  cedearItem("AMD", "AMD CEDEAR reference", "Technology", 3),
  cedearItem("INTC", "Intel CEDEAR reference", "Technology", 3),
  cedearItem("NFLX", "Netflix CEDEAR reference", "Communication Services", 3),
  cedearItem("MELI", "MercadoLibre CEDEAR reference", "Consumer Discretionary", 3),
  cedearItem("BABA", "Alibaba CEDEAR reference", "Consumer Discretionary", 3),
  cedearItem("KO", "Coca-Cola CEDEAR reference", "Consumer Staples", 3),
  cedearItem("PEP", "PepsiCo CEDEAR reference", "Consumer Staples", 3),
  cedearItem("MCD", "McDonald's CEDEAR reference", "Consumer Discretionary", 3),
  cedearItem("WMT", "Walmart CEDEAR reference", "Consumer Staples", 3),
  cedearItem("COST", "Costco CEDEAR reference", "Consumer Staples", 3),
  cedearItem("PG", "Procter & Gamble CEDEAR reference", "Consumer Staples", 3),
  cedearItem("JNJ", "Johnson & Johnson CEDEAR reference", "Healthcare", 3),
  cedearItem("JPM", "JPMorgan Chase CEDEAR reference", "Financials", 3),
  cedearItem("BAC", "Bank of America CEDEAR reference", "Financials", 3),
  cedearItem("V", "Visa CEDEAR reference", "Financials", 3),
  cedearItem("MA", "Mastercard CEDEAR reference", "Financials", 3),
  cedearItem("BRKB", "Berkshire Hathaway CEDEAR reference", "Financials", 3),
  cedearItem("SPY", "SPY CEDEAR reference", "ETF", 5),
  cedearItem("QQQ", "QQQ CEDEAR reference", "ETF", 5),
  cedearItem("DIA", "DIA CEDEAR reference", "ETF", 3),
  cedearItem("IWM", "IWM CEDEAR reference", "ETF", 3),
  cedearItem("XLE", "XLE CEDEAR reference", "ETF", 3),
  cedearItem("GLD", "GLD CEDEAR reference", "ETF", 3),
  cedearItem("SLV", "SLV CEDEAR reference", "ETF", 3),
  cedearItem("XOM", "Exxon Mobil CEDEAR reference", "Energy", 3),
  cedearItem("CVX", "Chevron CEDEAR reference", "Energy", 3),
  cedearItem("VALE", "Vale CEDEAR reference", "Materials", 3),
  cedearItem("PBR", "Petrobras CEDEAR reference", "Energy", 3),
];
