import type { InstrumentUniverseItem } from "./types";

const realSupported = new Set([
  "AAPL",
  "MSFT",
  "NVDA",
  "AMZN",
  "META",
  "GOOGL",
  "TSLA",
  "NFLX",
  "AMD",
  "INTC",
  "JPM",
  "BAC",
  "KO",
  "PEP",
  "WMT",
  "DIS",
  "V",
  "MA",
  "XOM",
  "CVX",
  "UNH",
  "JNJ",
  "PG",
  "COST",
  "MCD",
  "NKE",
  "CRM",
  "ORCL",
  "IBM",
  "SPY",
  "QQQ",
  "DIA",
  "IWM",
  "GLD",
  "SLV",
  "TLT",
  "HYG",
  "VOO",
  "VTI",
]);

const usItems = [
  ["AAPL", "Apple Inc.", "NASDAQ", "Technology"],
  ["MSFT", "Microsoft Corporation", "NASDAQ", "Technology"],
  ["NVDA", "NVIDIA Corporation", "NASDAQ", "Technology"],
  ["TSLA", "Tesla Inc.", "NASDAQ", "Consumer Discretionary"],
  ["AMZN", "Amazon.com Inc.", "NASDAQ", "Consumer Discretionary"],
  ["META", "Meta Platforms Inc.", "NASDAQ", "Communication Services"],
  ["GOOGL", "Alphabet Inc.", "NASDAQ", "Communication Services"],
  ["AMD", "Advanced Micro Devices Inc.", "NASDAQ", "Technology"],
  ["INTC", "Intel Corporation", "NASDAQ", "Technology"],
  ["NFLX", "Netflix Inc.", "NASDAQ", "Communication Services"],
  ["MELI", "MercadoLibre Inc.", "NASDAQ", "Consumer Discretionary"],
  ["BABA", "Alibaba Group Holding Ltd.", "NYSE", "Consumer Discretionary"],
  ["KO", "The Coca-Cola Company", "NYSE", "Consumer Staples"],
  ["PEP", "PepsiCo Inc.", "NASDAQ", "Consumer Staples"],
  ["MCD", "McDonald's Corporation", "NYSE", "Consumer Discretionary"],
  ["WMT", "Walmart Inc.", "NYSE", "Consumer Staples"],
  ["DIS", "The Walt Disney Company", "NYSE", "Communication Services"],
  ["COST", "Costco Wholesale Corporation", "NASDAQ", "Consumer Staples"],
  ["PG", "Procter & Gamble Company", "NYSE", "Consumer Staples"],
  ["JNJ", "Johnson & Johnson", "NYSE", "Healthcare"],
  ["UNH", "UnitedHealth Group Incorporated", "NYSE", "Healthcare"],
  ["JPM", "JPMorgan Chase & Co.", "NYSE", "Financials"],
  ["BAC", "Bank of America Corporation", "NYSE", "Financials"],
  ["V", "Visa Inc.", "NYSE", "Financials"],
  ["MA", "Mastercard Incorporated", "NYSE", "Financials"],
  ["NKE", "NIKE Inc.", "NYSE", "Consumer Discretionary"],
  ["CRM", "Salesforce Inc.", "NYSE", "Technology"],
  ["ORCL", "Oracle Corporation", "NYSE", "Technology"],
  ["IBM", "International Business Machines Corporation", "NYSE", "Technology"],
  ["BRKB", "Berkshire Hathaway Inc.", "NYSE", "Financials"],
  ["SPY", "SPDR S&P 500 ETF Trust", "NYSE_ARCA", "ETF"],
  ["QQQ", "Invesco QQQ Trust", "NASDAQ", "ETF"],
  ["DIA", "SPDR Dow Jones Industrial Average ETF", "NYSE_ARCA", "ETF"],
  ["IWM", "iShares Russell 2000 ETF", "NYSE_ARCA", "ETF"],
  ["XLE", "Energy Select Sector SPDR Fund", "NYSE_ARCA", "ETF"],
  ["GLD", "SPDR Gold Shares", "NYSE_ARCA", "ETF"],
  ["SLV", "iShares Silver Trust", "NYSE_ARCA", "ETF"],
  ["TLT", "iShares 20+ Year Treasury Bond ETF", "NASDAQ", "ETF"],
  ["HYG", "iShares iBoxx High Yield Corporate Bond ETF", "NYSE_ARCA", "ETF"],
  ["VOO", "Vanguard S&P 500 ETF", "NYSE_ARCA", "ETF"],
  ["VTI", "Vanguard Total Stock Market ETF", "NYSE_ARCA", "ETF"],
  ["XOM", "Exxon Mobil Corporation", "NYSE", "Energy"],
  ["CVX", "Chevron Corporation", "NYSE", "Energy"],
  ["VALE", "Vale S.A.", "NYSE", "Materials"],
  ["PBR", "Petrobras", "NYSE", "Energy"],
] as const;

export const US_INSTRUMENT_UNIVERSE: InstrumentUniverseItem[] = usItems.map(
  ([symbol, displayName, market, sector], index) => ({
    symbol,
    displayName,
    category: sector === "ETF" ? "etf" : "equity",
    country: "US",
    market,
    currency: "USD",
    globalTicker: symbol,
    displayCurrency: "USD",
    tradingCurrency: "USD",
    settlementCurrency: "USD",
    sector,
    exchange: market,
    primarySymbol: symbol,
    underlyingSymbol: symbol,
    relatedSymbols: [symbol],
    isPrimary: true,
    isSearchable: true,
    sourceStatus: realSupported.has(symbol) ? "real_supported" : "future_supported",
    dataCoverage: {
      price: realSupported.has(symbol),
      technical: realSupported.has(symbol),
      fundamentals: realSupported.has(symbol),
      fixedIncome: false,
      news: false,
    },
    searchableAliases: [`${symbol} USA`, `${symbol} US stock`, `${symbol} NYSE`, `${symbol} NASDAQ`],
    tags: ["usa", "stock", sector.toLowerCase()],
    priority: realSupported.has(symbol) ? 9 - index * 0.05 : 5 - index * 0.1,
  }),
);
