import type { AlertAssetType, AlertRuleDefinition } from "./types";

const TECHNICAL_ASSET_TYPES: AlertAssetType[] = ["stock", "etf", "adr", "cedear", "cedear_etf", "crypto"];
const RELEASED_AT = "2026-08-05T00:00:00.000Z";

export const alertRuleCatalog: AlertRuleDefinition[] = [
  {
    id: "unusual_price_move",
    version: 1,
    name: "Volatility-adjusted unusual price move",
    category: "unusual_price_move",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: true,
    description: "Compares the latest return with recent realized volatility and ATR; it does not use a universal percentage.",
    requiredData: ["OHLCV >= 60 bars", "ATR14", "observedAt", "provider"],
    cooldownMinutes: 360,
    limitations: ["Market and sector context are not yet available."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "unusual_volume",
    version: 1,
    name: "Liquidity-adjusted unusual volume",
    category: "unusual_volume",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: true,
    description: "Compares the latest complete bar volume with the prior 20-bar baseline when volume is usable.",
    requiredData: ["OHLCV >= 30 bars", "positive volume", "observedAt", "provider"],
    cooldownMinutes: 360,
    limitations: ["Disabled automatically when the provider does not publish usable volume."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "trend_change",
    version: 1,
    name: "Trend break or recovery",
    category: "trend_change",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: true,
    description: "Detects a confirmed cross of EMA50 or the prior 20-bar range with an ATR buffer.",
    requiredData: ["OHLCV >= 60 bars", "EMA50", "ATR14", "observedAt", "provider"],
    cooldownMinutes: 720,
    limitations: ["A technical break is informational and is not an order."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "elevated_volatility",
    version: 1,
    name: "Elevated realized volatility",
    category: "elevated_volatility",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: true,
    description: "Compares recent 10-bar realized volatility with the instrument's own preceding baseline.",
    requiredData: ["OHLCV >= 60 bars", "observedAt", "provider"],
    cooldownMinutes: 720,
    limitations: ["Realized volatility describes price dispersion, not future direction."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "multi_signal_opportunity",
    version: 1,
    name: "Multi-signal opportunity",
    category: "opportunity",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: true,
    description: "Requires an upward trend event plus independent price or volume confirmation and fresh data.",
    requiredData: ["two independent triggered rules", "fresh OHLCV", "provider healthy"],
    cooldownMinutes: 1440,
    limitations: ["Opportunity means a setup worth reviewing, not an expected gain."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "material_news",
    version: 1,
    name: "Material news",
    category: "material_news",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: false,
    description: "Reserved for a licensed, attributable news source.",
    requiredData: ["licensed news source", "source URL", "publishedAt"],
    cooldownMinutes: 720,
    limitations: ["No validated material-news source is configured."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "bond_event",
    version: 1,
    name: "Fixed-income event",
    category: "bond_event",
    supportedAssetTypes: ["bond", "bill"],
    enabled: false,
    description: "Reserved for verified price, cash-flow, yield and liquidity data.",
    requiredData: ["real price", "official cash flows", "verified yield"],
    cooldownMinutes: 1440,
    limitations: ["Current fixed-income coverage is mock or incomplete."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "corporate_bond_event",
    version: 1,
    name: "Corporate-bond event",
    category: "corporate_bond_event",
    supportedAssetTypes: ["corporate_bond"],
    enabled: false,
    description: "Reserved for verified issuer, cash-flow, yield and liquidity data.",
    requiredData: ["real price", "official cash flows", "issuer event source"],
    cooldownMinutes: 1440,
    limitations: ["No validated corporate-bond data source is configured."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "arbitrage_opportunity",
    version: 1,
    name: "Arbitrage opportunity",
    category: "arbitrage_opportunity",
    supportedAssetTypes: [],
    enabled: false,
    description: "Future integration point only; excluded from this phase.",
    requiredData: [],
    cooldownMinutes: 60,
    limitations: ["Radar de Arbitraje is outside this module's scope."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
];

export function enabledRuleCatalog() {
  return alertRuleCatalog.filter((rule) => rule.enabled);
}
