import type { AlertAssetType, AlertRuleDefinition } from "./types";

const TECHNICAL_ASSET_TYPES: AlertAssetType[] = ["stock", "etf", "adr", "cedear", "cedear_etf", "crypto"];
const RELEASED_AT = "2026-08-05T00:00:00.000Z";

export const alertRuleCatalog: AlertRuleDefinition[] = [
  {
    id: "unusual_price_move",
    version: 1,
    name: "Volatility-adjusted unusual price move",
    category: "unusual_price_move",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: true,
    scope: "automatic",
    description: "Compares the latest return with recent realized volatility and ATR; it does not use a universal percentage.",
    requiredData: ["OHLCV >= 60 bars", "ATR14", "observedAt", "provider"],
    cooldownMinutes: 360,
    limitations: ["Market and sector context are not yet available."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "unusual_volume",
    version: 1,
    name: "Liquidity-adjusted unusual volume",
    category: "unusual_volume",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: true,
    scope: "automatic",
    description: "Compares the latest complete bar volume with the prior 20-bar baseline when volume is usable.",
    requiredData: ["OHLCV >= 30 bars", "positive volume", "observedAt", "provider"],
    cooldownMinutes: 360,
    limitations: ["Disabled automatically when the provider does not publish usable volume."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "trend_change",
    version: 1,
    name: "Trend break or recovery",
    category: "trend_change",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: true,
    scope: "automatic",
    description: "Detects a confirmed cross of EMA50 or the prior 20-bar range with an ATR buffer.",
    requiredData: ["OHLCV >= 60 bars", "EMA50", "ATR14", "observedAt", "provider"],
    cooldownMinutes: 720,
    limitations: ["A technical break is informational and is not an order."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "elevated_volatility",
    version: 1,
    name: "Elevated realized volatility",
    category: "elevated_volatility",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: true,
    scope: "automatic",
    description: "Compares recent 10-bar realized volatility with the instrument's own preceding baseline.",
    requiredData: ["OHLCV >= 60 bars", "observedAt", "provider"],
    cooldownMinutes: 720,
    limitations: ["Realized volatility describes price dispersion, not future direction."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "multi_signal_opportunity",
    version: 1,
    name: "Multi-signal opportunity",
    category: "opportunity",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: true,
    scope: "automatic",
    description: "Requires an upward trend event plus independent price or volume confirmation and fresh data.",
    requiredData: ["two independent triggered rules", "fresh OHLCV", "provider healthy"],
    cooldownMinutes: 1440,
    limitations: ["Opportunity means a setup worth reviewing, not an expected gain."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "material_news",
    version: 1,
    name: "Material news",
    category: "material_news",
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: false,
    scope: "automatic",
    description: "Reserved for a licensed, attributable news source.",
    requiredData: ["licensed news source", "source URL", "publishedAt"],
    cooldownMinutes: 720,
    limitations: ["No validated material-news source is configured."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "bond_event",
    version: 1,
    name: "Fixed-income event",
    category: "bond_event",
    supportedAssetTypes: ["bond", "bill"],
    enabled: false,
    scope: "automatic",
    description: "Reserved for verified price, cash-flow, yield and liquidity data.",
    requiredData: ["real price", "official cash flows", "verified yield"],
    cooldownMinutes: 1440,
    limitations: ["Current fixed-income coverage is mock or incomplete."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "corporate_bond_event",
    version: 1,
    name: "Corporate-bond event",
    category: "corporate_bond_event",
    supportedAssetTypes: ["corporate_bond"],
    enabled: false,
    scope: "automatic",
    description: "Reserved for verified issuer, cash-flow, yield and liquidity data.",
    requiredData: ["real price", "official cash flows", "issuer event source"],
    cooldownMinutes: 1440,
    limitations: ["No validated corporate-bond data source is configured."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  {
    id: "arbitrage_opportunity",
      version: 4,
    name: "Arbitrage quote difference",
    category: "arbitrage_opportunity",
    supportedAssetTypes: [],
    enabled: true,
    scope: "personal",
      description: "Monitors either a configured comparison or the full Radar and alerts when a recent gross difference reaches the configured per-USD threshold.",
      requiredData: ["source ask", "destination bid", "recent CMA retrieval", "comparable asset", "configured per-USD threshold"],
    cooldownMinutes: 60,
    limitations: ["A gross difference is not net profit; amount, costs, limits and transfer availability must be evaluated separately."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  },
  ...[
    ["personal_price_above", "Price crosses above target", "technical_change"],
    ["personal_price_below", "Price crosses below target", "technical_change"],
    ["personal_rapid_rise", "Configured sharp rise", "unusual_price_move"],
    ["personal_rapid_fall", "Configured sharp fall", "unusual_price_move"],
    ["personal_near_ema200", "Price approaches EMA 200", "technical_change"],
    ["personal_near_period_low", "Price approaches period low", "technical_change"],
    ["personal_near_period_high", "Price approaches period high", "technical_change"],
  ].map(([id, name, category]) => ({
    id,
    version: 1,
    name,
    category: category as AlertRuleDefinition["category"],
    supportedAssetTypes: TECHNICAL_ASSET_TYPES,
    enabled: true,
    scope: "personal" as const,
    description: "User-configured deterministic condition evaluated from provider OHLCV data.",
    requiredData: ["configured threshold", "fresh OHLCV", "observedAt", "provider"],
    cooldownMinutes: 60,
    limitations: ["The condition is informational and does not execute an order."],
    createdAt: RELEASED_AT,
    updatedAt: RELEASED_AT,
  })),
];

export function enabledRuleCatalog() {
  return alertRuleCatalog.filter((rule) => rule.enabled);
}
