import type { FxProvider, TransferAsset } from "./types";

function referenceProvider(id: string, name: string, providerType: FxProvider["providerType"], websiteUrl?: string): FxProvider {
  return {
    id,
    name,
    providerType,
    websiteUrl,
    operates24x7: true,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "unverified", availability24x7: "reference_only" },
  };
}

const STABLECOIN_REFERENCE_PROVIDERS: FxProvider[] = [
  referenceProvider("astropay", "AstroPay", "wallet", "https://www.astropay.com/"),
  referenceProvider("binance", "Binance", "exchange", "https://www.binance.com/"),
  referenceProvider("binancep2p", "Binance P2P", "exchange", "https://p2p.binance.com/"),
  referenceProvider("bitgetp2p", "Bitget P2P", "exchange", "https://www.bitget.com/p2p-trade"),
  referenceProvider("bitsoalpha", "Bitso Alpha", "exchange", "https://bitso.com/"),
  referenceProvider("buenbit", "Buenbit", "exchange", "https://www.buenbit.com/"),
  referenceProvider("bybit", "Bybit", "exchange", "https://www.bybit.com/"),
  referenceProvider("bybitp2p", "Bybit P2P", "exchange", "https://www.bybit.com/fiat/trade/otc"),
  referenceProvider("cocoscrypto", "Cocos Crypto", "exchange", "https://cocos.capital/"),
  referenceProvider("decrypto", "Decrypto", "exchange", "https://decrypto.la/"),
  referenceProvider("kucoinp2p", "KuCoin P2P", "exchange", "https://www.kucoin.com/otc"),
  referenceProvider("lemoncash", "Lemon", "wallet", "https://lemon.me/"),
  referenceProvider("letsbit", "Let'sBit", "exchange", "https://letsbit.io/"),
  referenceProvider("mexcp2p", "MEXC P2P", "exchange", "https://www.mexc.com/fiat-p2p"),
  referenceProvider("nexo", "Nexo", "exchange", "https://nexo.com/"),
  referenceProvider("okexp2p", "OKX P2P", "exchange", "https://www.okx.com/p2p-markets"),
  referenceProvider("ripio", "Ripio", "exchange", "https://www.ripio.com/"),
  referenceProvider("ripioexchange", "Ripio Trade", "exchange", "https://www.ripiotrade.co/"),
  referenceProvider("tiendacrypto", "Tienda Crypto", "exchange", "https://tiendacrypto.com/"),
  referenceProvider("vitawallet", "Vita Wallet", "wallet", "https://vitawallet.io/"),
  referenceProvider("wallbit", "Wallbit", "wallet", "https://wallbit.io/"),
];

export const ARBITRAGE_PROVIDERS: FxProvider[] = [
  {
    id: "plus",
    name: "Plus",
    legalName: "Global Fintech S.A.",
    providerType: "exchange_agency",
    websiteUrl: "https://plus.com.ar/operar/",
    operates24x7: false,
    supportsArsDeposit: true,
    supportsArsWithdrawal: true,
    supportsUsdDeposit: true,
    supportsUsdWithdrawal: true,
    requiresSameHolderAccount: true,
    sourceType: "public_endpoint",
    status: "active",
    verification: { deposit: "partially_verified", withdrawal: "partially_verified", sameHolder: "partially_verified", transferAsset: "partially_verified", availability24x7: "unverified" },
  },
  {
    id: "bna",
    name: "Banco Nación",
    legalName: "Banco de la Nación Argentina",
    providerType: "bank",
    websiteUrl: "https://www.bna.com.ar/Empresas",
    operates24x7: false,
    supportsArsDeposit: true,
    supportsArsWithdrawal: true,
    supportsUsdDeposit: true,
    supportsUsdWithdrawal: true,
    requiresSameHolderAccount: true,
    sourceType: "public_page",
    status: "active",
    verification: { deposit: "partially_verified", withdrawal: "partially_verified", sameHolder: "partially_verified", transferAsset: "partially_verified", availability24x7: "verified" },
  },
  {
    id: "belo",
    name: "Belo",
    providerType: "wallet",
    websiteUrl: "https://www.belo.app/",
    operates24x7: true,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "unverified", availability24x7: "reference_only" },
  },
  {
    id: "dolarapp",
    name: "DolarApp",
    providerType: "wallet",
    websiteUrl: "https://www.dolarapp.com/",
    operates24x7: true,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "unverified", availability24x7: "reference_only" },
  },
  {
    id: "satoshitango",
    name: "Satoshi Tango",
    providerType: "exchange",
    websiteUrl: "https://www.satoshitango.com/",
    operates24x7: true,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "unverified", availability24x7: "reference_only" },
  },
  {
    id: "fiwind",
    name: "Fiwind",
    providerType: "wallet",
    websiteUrl: "https://www.fiwind.io/",
    operates24x7: true,
    sourceType: "aggregator",
    status: "active",
    supportsUsdDeposit: true,
    supportsUsdWithdrawal: true,
    requiresSameHolderAccount: true,
    verification: { deposit: "partially_verified", withdrawal: "partially_verified", sameHolder: "verified", transferAsset: "partially_verified", availability24x7: "partially_verified" },
  },
  ...STABLECOIN_REFERENCE_PROVIDERS,
  {
    id: "banco-ciudad",
    name: "Banco Ciudad",
    providerType: "bank",
    websiteUrl: "https://www.bancociudad.com.ar/",
    operates24x7: false,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "partially_verified", availability24x7: "reference_only" },
  },
  {
    id: "banco-hipotecario",
    name: "Banco Hipotecario",
    providerType: "bank",
    websiteUrl: "https://www.hipotecario.com.ar/",
    operates24x7: false,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "partially_verified", availability24x7: "reference_only" },
  },
  {
    id: "banco-provincia",
    name: "Banco Provincia",
    providerType: "bank",
    websiteUrl: "https://www.bancoprovincia.com.ar/",
    operates24x7: false,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "partially_verified", availability24x7: "reference_only" },
  },
  {
    id: "banco-supervielle",
    name: "Banco Supervielle",
    providerType: "bank",
    websiteUrl: "https://www.supervielle.com.ar/",
    operates24x7: false,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "partially_verified", availability24x7: "reference_only" },
  },
  {
    id: "bancor",
    name: "Bancor",
    providerType: "bank",
    websiteUrl: "https://www.bancor.com.ar/",
    operates24x7: false,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "partially_verified", availability24x7: "reference_only" },
  },
  {
    id: "brubank",
    name: "Brubank",
    providerType: "bank",
    websiteUrl: "https://www.brubank.com/",
    operates24x7: false,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "partially_verified", availability24x7: "reference_only" },
  },
  {
    id: "uala",
    name: "Ualá",
    providerType: "wallet",
    websiteUrl: "https://www.uala.com.ar/",
    operates24x7: true,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "partially_verified", availability24x7: "reference_only" },
  },
  {
    id: "reba",
    name: "Reba",
    providerType: "wallet",
    websiteUrl: "https://www.reba.com.ar/",
    operates24x7: true,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "partially_verified", availability24x7: "reference_only" },
  },
  {
    id: "tiendadolar",
    name: "Tienda Dólar",
    providerType: "exchange_agency",
    websiteUrl: "https://tiendadolar.com/",
    operates24x7: false,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "partially_verified", availability24x7: "reference_only" },
  },
  {
    id: "balanz",
    name: "Balanz",
    providerType: "broker",
    websiteUrl: "https://balanz.com/",
    operates24x7: false,
    sourceType: "aggregator",
    status: "active",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "partially_verified", availability24x7: "reference_only" },
  },
  {
    id: "galicia",
    name: "Banco Galicia",
    providerType: "bank",
    websiteUrl: "https://www.galicia.ar/personas",
    sourceType: "unavailable",
    status: "unsupported",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "unverified", availability24x7: "unverified" },
  },
  {
    id: "santander",
    name: "Santander Argentina",
    providerType: "bank",
    websiteUrl: "https://www.santander.com.ar/",
    sourceType: "unavailable",
    status: "unsupported",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "unverified", availability24x7: "unverified" },
  },
  {
    id: "bbva",
    name: "BBVA Argentina",
    providerType: "bank",
    websiteUrl: "https://www.bbva.com.ar/",
    sourceType: "unavailable",
    status: "unsupported",
    verification: { deposit: "unverified", withdrawal: "unverified", sameHolder: "unverified", transferAsset: "unverified", availability24x7: "unverified" },
  },
];

export function getArbitrageProvider(id: string) {
  return ARBITRAGE_PROVIDERS.find((provider) => provider.id === id);
}

export function supportsDeposit(provider: FxProvider, asset: TransferAsset) {
  if (asset === "USD_BANK") return provider.supportsUsdDeposit;
  if (asset === "USDT") return provider.supportsUsdtDeposit;
  return provider.supportsUsdcDeposit;
}

export function supportsWithdrawal(provider: FxProvider, asset: TransferAsset) {
  if (asset === "USD_BANK") return provider.supportsUsdWithdrawal;
  if (asset === "USDT") return provider.supportsUsdtWithdrawal;
  return provider.supportsUsdcWithdrawal;
}
