import type { CnvDocument } from "./cnv-types";

const sourceLabel = "Structured demo document";

export const cnvMockDocuments: CnvDocument[] = [
  {
    id: "ggal-2026-q1-financial-statement-demo",
    symbol: "GGAL",
    issuerName: "Grupo Financiero Galicia",
    documentType: "financial_statement",
    title: "Estados financieros trimestrales",
    publishedAt: "2026-05-10",
    period: "1T 2026",
    source: "structured_demo",
    sourceLabel,
    url: null,
    isOfficialSource: false,
    isMock: true,
    summary: "Documento estructurado de demostracion para modelar futuros estados financieros CNV.",
  },
  {
    id: "ggal-2026-relevant-event-demo",
    symbol: "GGAL",
    issuerName: "Grupo Financiero Galicia",
    documentType: "relevant_event",
    title: "Hecho relevante",
    publishedAt: "2026-04-18",
    source: "structured_demo",
    sourceLabel,
    url: null,
    isOfficialSource: false,
    isMock: true,
    summary: "Placeholder para hechos relevantes hasta integrar una fuente oficial o publica autorizada.",
  },
  {
    id: "ypfd-2026-q1-financial-statement-demo",
    symbol: "YPFD",
    issuerName: "YPF S.A.",
    documentType: "financial_statement",
    title: "Estados financieros trimestrales",
    publishedAt: "2026-05-12",
    period: "1T 2026",
    source: "structured_demo",
    sourceLabel,
    url: null,
    isOfficialSource: false,
    isMock: true,
    summary: "Documento estructurado de demostracion para seguimiento de resultados y deuda.",
  },
  {
    id: "ypfd-2026-relevant-event-demo",
    symbol: "YPFD",
    issuerName: "YPF S.A.",
    documentType: "relevant_event",
    title: "Hecho relevante",
    publishedAt: "2026-04-26",
    source: "structured_demo",
    sourceLabel,
    url: null,
    isOfficialSource: false,
    isMock: true,
    summary: "Placeholder para eventos societarios relevantes hasta habilitar integracion CNV real.",
  },
  {
    id: "pamp-2026-financial-statement-demo",
    symbol: "PAMP",
    issuerName: "Pampa Energia",
    documentType: "financial_statement",
    title: "Estados financieros",
    publishedAt: "2026-05-08",
    period: "2026",
    source: "structured_demo",
    sourceLabel,
    url: null,
    isOfficialSource: false,
    isMock: true,
    summary: "Documento estructurado de demostracion para analizar fundamentos de emisoras locales.",
  },
  {
    id: "byma-2026-corporate-info-demo",
    symbol: "BYMA",
    issuerName: "Bolsas y Mercados Argentinos",
    documentType: "board_decision",
    title: "Informacion societaria",
    publishedAt: "2026-04-30",
    source: "structured_demo",
    sourceLabel,
    url: null,
    isOfficialSource: false,
    isMock: true,
    summary: "Placeholder de informacion societaria hasta contar con integracion oficial CNV.",
  },
];
