import type { CnvIssuer } from "./cnv-types";

export const cnvIssuers: CnvIssuer[] = [
  {
    symbol: "GGAL",
    issuerName: "Grupo Financiero Galicia",
    market: "BYMA",
    sector: "Financials",
    cnvProfileUrl: null,
    website: null,
    localTicker: "GGAL",
    relatedAdr: "GGAL",
    sourceStatus: "future",
  },
  {
    symbol: "YPFD",
    issuerName: "YPF S.A.",
    market: "BYMA",
    sector: "Energy",
    cnvProfileUrl: null,
    website: null,
    localTicker: "YPFD",
    relatedAdr: "YPF",
    sourceStatus: "future",
  },
  {
    symbol: "PAMP",
    issuerName: "Pampa Energia",
    market: "BYMA",
    sector: "Utilities",
    cnvProfileUrl: null,
    website: null,
    localTicker: "PAMP",
    relatedAdr: "PAM",
    sourceStatus: "future",
  },
  {
    symbol: "TXAR",
    issuerName: "Ternium Argentina",
    market: "BYMA",
    sector: "Materials",
    cnvProfileUrl: null,
    website: null,
    localTicker: "TXAR",
    sourceStatus: "future",
  },
  {
    symbol: "ALUA",
    issuerName: "Aluar",
    market: "BYMA",
    sector: "Materials",
    cnvProfileUrl: null,
    website: null,
    localTicker: "ALUA",
    sourceStatus: "future",
  },
  {
    symbol: "TGSU2",
    issuerName: "Transportadora de Gas del Sur",
    market: "BYMA",
    sector: "Energy infrastructure",
    cnvProfileUrl: null,
    website: null,
    localTicker: "TGSU2",
    relatedAdr: "TGS",
    sourceStatus: "future",
  },
  {
    symbol: "CEPU",
    issuerName: "Central Puerto",
    market: "BYMA",
    sector: "Utilities",
    cnvProfileUrl: null,
    website: null,
    localTicker: "CEPU",
    relatedAdr: "CEPU",
    sourceStatus: "future",
  },
  {
    symbol: "COME",
    issuerName: "Sociedad Comercial del Plata",
    market: "BYMA",
    sector: "Holding company",
    cnvProfileUrl: null,
    website: null,
    localTicker: "COME",
    sourceStatus: "future",
  },
  {
    symbol: "BYMA",
    issuerName: "Bolsas y Mercados Argentinos",
    market: "BYMA",
    sector: "Market infrastructure",
    cnvProfileUrl: null,
    website: null,
    localTicker: "BYMA",
    sourceStatus: "future",
  },
  {
    symbol: "SUPV",
    issuerName: "Grupo Supervielle",
    market: "BYMA",
    sector: "Financials",
    cnvProfileUrl: null,
    website: null,
    localTicker: "SUPV",
    relatedAdr: "SUPV",
    sourceStatus: "future",
  },
  {
    symbol: "VALO",
    issuerName: "Banco de Valores",
    market: "BYMA",
    sector: "Financials",
    cnvProfileUrl: null,
    website: null,
    localTicker: "VALO",
    sourceStatus: "future",
  },
];

export function normalizeCnvSymbol(symbol: string) {
  return symbol.trim().toUpperCase();
}

export function getCnvIssuerFromRegistry(symbol: string) {
  const normalized = normalizeCnvSymbol(symbol);
  return cnvIssuers.find((issuer) => issuer.symbol === normalized) ?? null;
}
