import type { CedearInstrument } from "./types";

// Los ratios y precios locales son datos estructurados simulados.
// En producción deben venir de BYMA, IOL, brokers o proveedores licenciados.
export const MOCK_REFERENCE_CCL = 1250;

export const mockCedears: CedearInstrument[] = [
  {
    localSymbol: "AAPL",
    underlyingSymbol: "AAPL",
    underlyingName: "Apple Inc.",
    localMarket: "BYMA",
    underlyingMarket: "NASDAQ",
    localCurrency: "ARS",
    underlyingCurrency: "USD",
    ratio: 20,
    localPrice: 12325,
    underlyingPrice: 197.24,
    sourceLabel: "Mock CEDEAR data",
    isMock: true,
    status: "mock",
  },
  {
    localSymbol: "MSFT",
    underlyingSymbol: "MSFT",
    underlyingName: "Microsoft Corporation",
    localMarket: "BYMA",
    underlyingMarket: "NASDAQ",
    localCurrency: "ARS",
    underlyingCurrency: "USD",
    ratio: 30,
    localPrice: 17825,
    underlyingPrice: 427.8,
    sourceLabel: "Mock CEDEAR data",
    isMock: true,
    status: "mock",
  },
  {
    localSymbol: "NVDA",
    underlyingSymbol: "NVDA",
    underlyingName: "NVIDIA Corporation",
    localMarket: "BYMA",
    underlyingMarket: "NASDAQ",
    localCurrency: "ARS",
    underlyingCurrency: "USD",
    ratio: 24,
    localPrice: 47570,
    underlyingPrice: 913.4,
    sourceLabel: "Mock CEDEAR data",
    isMock: true,
    status: "mock",
  },
  {
    localSymbol: "TSLA",
    underlyingSymbol: "TSLA",
    underlyingName: "Tesla Inc.",
    localMarket: "BYMA",
    underlyingMarket: "NASDAQ",
    localCurrency: "ARS",
    underlyingCurrency: "USD",
    ratio: 15,
    localPrice: 15185,
    underlyingPrice: 182.2,
    sourceLabel: "Mock CEDEAR data",
    isMock: true,
    status: "mock",
  },
  {
    localSymbol: "AMZN",
    underlyingSymbol: "AMZN",
    underlyingName: "Amazon.com Inc.",
    localMarket: "BYMA",
    underlyingMarket: "NASDAQ",
    localCurrency: "ARS",
    underlyingCurrency: "USD",
    ratio: 72,
    localPrice: 3190,
    underlyingPrice: 183.7,
    sourceLabel: "Mock CEDEAR data",
    isMock: true,
    status: "mock",
  },
  {
    localSymbol: "META",
    underlyingSymbol: "META",
    underlyingName: "Meta Platforms Inc.",
    localMarket: "BYMA",
    underlyingMarket: "NASDAQ",
    localCurrency: "ARS",
    underlyingCurrency: "USD",
    ratio: 8,
    localPrice: 74700,
    underlyingPrice: 478.2,
    sourceLabel: "Mock CEDEAR data",
    isMock: true,
    status: "mock",
  },
  {
    localSymbol: "GOOGL",
    underlyingSymbol: "GOOGL",
    underlyingName: "Alphabet Inc.",
    localMarket: "BYMA",
    underlyingMarket: "NASDAQ",
    localCurrency: "ARS",
    underlyingCurrency: "USD",
    ratio: 58,
    localPrice: 3765,
    underlyingPrice: 174.6,
    sourceLabel: "Mock CEDEAR data",
    isMock: true,
    status: "mock",
  },
  {
    localSymbol: "KO",
    underlyingSymbol: "KO",
    underlyingName: "The Coca-Cola Company",
    localMarket: "BYMA",
    underlyingMarket: "NYSE",
    localCurrency: "ARS",
    underlyingCurrency: "USD",
    ratio: 5,
    localPrice: 17450,
    underlyingPrice: 69.8,
    sourceLabel: "Mock CEDEAR data",
    isMock: true,
    status: "mock",
  },
  {
    localSymbol: "SPY",
    underlyingSymbol: "SPY",
    underlyingName: "SPDR S&P 500 ETF Trust",
    localMarket: "BYMA",
    underlyingMarket: "NYSE_ARCA",
    localCurrency: "ARS",
    underlyingCurrency: "USD",
    ratio: 20,
    localPrice: 37310,
    underlyingPrice: 596.9,
    sourceLabel: "Mock CEDEAR data",
    isMock: true,
    status: "mock",
  },
  {
    localSymbol: "QQQ",
    underlyingSymbol: "QQQ",
    underlyingName: "Invesco QQQ Trust",
    localMarket: "BYMA",
    underlyingMarket: "NASDAQ",
    localCurrency: "ARS",
    underlyingCurrency: "USD",
    ratio: 20,
    localPrice: 30940,
    underlyingPrice: 495.1,
    sourceLabel: "Mock CEDEAR data",
    isMock: true,
    status: "mock",
  },
];

export function getMockCedear(symbol: string) {
  const normalized = symbol.trim().toUpperCase();
  return mockCedears.find((item) => item.localSymbol === normalized || item.underlyingSymbol === normalized) ?? null;
}
