import type { Asset, MarketOverviewItem } from "@/types/asset";

export const financialDisclaimer =
  "This platform provides informational analysis only and does not constitute personalized financial advice.";

export const marketOverviewItems: MarketOverviewItem[] = [
  { name: "S&P 500", value: "5,218.42", dailyChange: 0.42, trend: "up", context: "Large-cap breadth improving" },
  { name: "Nasdaq 100", value: "18,142.80", dailyChange: -0.18, trend: "down", context: "Mega-cap tech cooling" },
  { name: "Merval", value: "1,418,220", dailyChange: 1.74, trend: "up", context: "Local equities bid" },
  { name: "Bitcoin", value: "64,280", dailyChange: 2.86, trend: "up", context: "Volatility elevated" },
  { name: "USDT/ARS", value: "1,105", dailyChange: 0.92, trend: "up", context: "Crypto dollar reference" },
  { name: "CCL reference", value: "1,128", dailyChange: -0.34, trend: "down", context: "FX spread watch" },
];

const baseMockAssets: Asset[] = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    type: "stock",
    typeLabel: "Stock",
    market: "NASDAQ",
    currency: "USD",
    price: 191.24,
    dailyChange: 0.84,
    technicalScore: 78,
    fundamentalScore: 82,
    riskLevel: "medium",
    summary: "Quality mega-cap profile with constructive technical recovery and resilient margins.",
    technical: {
      sma20: 188.4,
      sma50: 184.2,
      sma200: 179.8,
      ema12: 190.1,
      ema26: 187.2,
      rsi14: 61.4,
      macd: "Positive crossover",
      atr: 3.42,
      bollingerBands: "Upper mid-band",
      volumeTrend: "Accumulation",
      support: 184.6,
      resistance: 196.8,
      signal: "Trend confirmation",
    },
    fundamentals: {
      peRatio: 28.7,
      pbRatio: 39.1,
      roe: 147.3,
      roa: 28.2,
      eps: 6.68,
      ebitdaMargin: 33.6,
      bookValuePerShare: 4.89,
      dividendYield: 0.52,
    },
    news: [
      {
        title: "Services revenue remains a quality driver",
        source: "Market Desk",
        sentiment: "positive",
        impact: "medium",
        summary: "Mock coverage points to durable services contribution and margin stability.",
      },
      {
        title: "Hardware cycle expectations stay measured",
        source: "Equity Monitor",
        sentiment: "neutral",
        impact: "medium",
        summary: "Investors continue to balance replacement-cycle optimism with valuation discipline.",
      },
    ],
  },
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    type: "etf",
    typeLabel: "ETF",
    market: "NYSE Arca",
    currency: "USD",
    price: 521.82,
    dailyChange: 0.38,
    technicalScore: 74,
    fundamentalScore: 70,
    riskLevel: "medium",
    summary: "Broad US equity exposure with stable trend structure and moderate valuation sensitivity.",
    technical: {
      sma20: 518.2,
      sma50: 512.7,
      sma200: 493.4,
      ema12: 520.3,
      ema26: 516.6,
      rsi14: 58.2,
      macd: "Positive",
      atr: 5.76,
      bollingerBands: "Center-upper channel",
      volumeTrend: "Stable",
      support: 511.4,
      resistance: 528.9,
      signal: "Bullish momentum",
    },
    fundamentals: {
      peRatio: 22.1,
      pbRatio: 4.3,
      roe: 19.8,
      roa: 8.7,
      eps: 23.62,
      ebitdaMargin: 22.4,
      bookValuePerShare: 121.2,
      dividendYield: 1.28,
    },
    news: [
      {
        title: "Index breadth improves after mixed macro prints",
        source: "Global Tape",
        sentiment: "positive",
        impact: "medium",
        summary: "Mock breadth indicators show wider participation beyond the largest constituents.",
      },
    ],
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    type: "etf",
    typeLabel: "ETF",
    market: "NASDAQ",
    currency: "USD",
    price: 443.16,
    dailyChange: -0.22,
    technicalScore: 69,
    fundamentalScore: 66,
    riskLevel: "medium",
    summary: "Growth-heavy exposure with strong secular themes and higher rate sensitivity.",
    technical: {
      sma20: 445.5,
      sma50: 438.9,
      sma200: 414.7,
      ema12: 442.7,
      ema26: 440.4,
      rsi14: 53.6,
      macd: "Flat positive",
      atr: 6.34,
      bollingerBands: "Middle band",
      volumeTrend: "Neutral",
      support: 432.8,
      resistance: 452.5,
      signal: "Neutral consolidation",
    },
    fundamentals: {
      peRatio: 29.4,
      pbRatio: 7.1,
      roe: 24.5,
      roa: 10.9,
      eps: 15.08,
      ebitdaMargin: 25.2,
      bookValuePerShare: 62.4,
      dividendYield: 0.61,
    },
    news: [
      {
        title: "Technology leadership pauses near highs",
        source: "ETF Radar",
        sentiment: "neutral",
        impact: "medium",
        summary: "Mock flow data suggests investors are waiting for earnings confirmation.",
      },
    ],
  },
  {
    symbol: "GGAL",
    name: "Grupo Financiero Galicia",
    type: "argentine_equity",
    typeLabel: "Argentine Equity / ADR / CEDEAR reference",
    market: "BYMA / NYSE",
    currency: "ARS/USD",
    price: 4360,
    dailyChange: 3.24,
    technicalScore: 83,
    fundamentalScore: 58,
    riskLevel: "very_high",
    summary: "High beta Argentina financial exposure tied to FX expectations and local liquidity.",
    argentinaContext: true,
    technical: {
      sma20: 4140,
      sma50: 3975,
      sma200: 3180,
      ema12: 4288,
      ema26: 4112,
      rsi14: 68.7,
      macd: "Strong positive",
      atr: 188,
      bollingerBands: "Upper band pressure",
      volumeTrend: "Rising",
      support: 4015,
      resistance: 4620,
      signal: "Breakout watch",
    },
    fundamentals: {
      peRatio: 9.8,
      pbRatio: 1.9,
      roe: 21.4,
      roa: 3.2,
      eps: 445.1,
      ebitdaMargin: 19.6,
      bookValuePerShare: 2294,
      dividendYield: 0.8,
    },
    news: [
      {
        title: "Financials react to local rate expectations",
        source: "Argentina Desk",
        sentiment: "positive",
        impact: "high",
        summary: "Mock market notes highlight sensitivity to policy rates, liquidity and sovereign risk.",
      },
    ],
  },
  {
    symbol: "YPFD",
    name: "YPF S.A.",
    type: "argentine_equity",
    typeLabel: "Argentine Equity / ADR / CEDEAR reference",
    market: "BYMA / NYSE",
    currency: "ARS/USD",
    price: 29750,
    dailyChange: 1.18,
    technicalScore: 72,
    fundamentalScore: 62,
    riskLevel: "high",
    summary: "Energy and Argentina macro exposure with operational upside and policy sensitivity.",
    argentinaContext: true,
    technical: {
      sma20: 29100,
      sma50: 27820,
      sma200: 23940,
      ema12: 29480,
      ema26: 28610,
      rsi14: 59.8,
      macd: "Positive",
      atr: 980,
      bollingerBands: "Upper middle",
      volumeTrend: "Stable accumulation",
      support: 28150,
      resistance: 30900,
      signal: "Trend confirmation",
    },
    fundamentals: {
      peRatio: 7.4,
      pbRatio: 1.2,
      roe: 16.1,
      roa: 5.4,
      eps: 4018,
      ebitdaMargin: 24.3,
      bookValuePerShare: 24791,
      dividendYield: 0,
    },
    news: [
      {
        title: "Energy names track crude and local regulation",
        source: "Commodities Desk",
        sentiment: "neutral",
        impact: "medium",
        summary: "Mock note flags crude prices, capital expenditure and local pricing rules.",
      },
    ],
  },
  {
    symbol: "BTC-USD",
    name: "Bitcoin",
    type: "crypto",
    typeLabel: "Crypto",
    market: "Crypto",
    currency: "USD",
    price: 64280,
    dailyChange: 2.86,
    technicalScore: 81,
    riskLevel: "very_high",
    summary: "Digital asset benchmark with positive momentum and structurally elevated volatility.",
    cryptoContext: true,
    technical: {
      sma20: 61750,
      sma50: 59210,
      sma200: 54880,
      ema12: 63420,
      ema26: 61840,
      rsi14: 64.9,
      macd: "Positive expansion",
      atr: 2410,
      bollingerBands: "Upper channel",
      volumeTrend: "Expanding",
      support: 60200,
      resistance: 66800,
      signal: "High volatility",
    },
    news: [
      {
        title: "Crypto volatility remains above traditional assets",
        source: "Crypto Monitor",
        sentiment: "neutral",
        impact: "high",
        summary: "Mock volatility regime points to wider intraday ranges and liquidity-driven moves.",
      },
    ],
  },
  {
    symbol: "ETH-USD",
    name: "Ethereum",
    type: "crypto",
    typeLabel: "Crypto",
    market: "Crypto",
    currency: "USD",
    price: 3184,
    dailyChange: 1.96,
    technicalScore: 76,
    riskLevel: "very_high",
    summary: "Smart-contract platform exposure with constructive trend but high beta to crypto liquidity.",
    cryptoContext: true,
    technical: {
      sma20: 3092,
      sma50: 2970,
      sma200: 2815,
      ema12: 3160,
      ema26: 3088,
      rsi14: 60.7,
      macd: "Positive",
      atr: 154,
      bollingerBands: "Upper middle",
      volumeTrend: "Stable",
      support: 2945,
      resistance: 3320,
      signal: "Bullish momentum",
    },
    news: [
      {
        title: "Network activity holds steady in mock dashboard",
        source: "Crypto Desk",
        sentiment: "positive",
        impact: "medium",
        summary: "Prepared placeholder for future on-chain and market microstructure inputs.",
      },
    ],
  },
  {
    symbol: "AL30",
    name: "Bonar 2030",
    type: "sovereign_bond",
    typeLabel: "Sovereign Bond",
    market: "BYMA",
    currency: "USD/ARS",
    price: 58.4,
    dailyChange: -0.66,
    technicalScore: 44,
    riskLevel: "very_high",
    summary: "Argentine sovereign bond with high yield, high volatility and FX-sensitive price behavior.",
    argentinaContext: true,
    technical: {
      sma20: 59.2,
      sma50: 57.7,
      sma200: 49.6,
      ema12: 58.8,
      ema26: 58.1,
      rsi14: 48.8,
      macd: "Neutral",
      atr: 1.82,
      bollingerBands: "Middle band",
      volumeTrend: "Choppy",
      support: 55.6,
      resistance: 61.8,
      signal: "Possible support test",
    },
    bondMetrics: {
      tir: 20.8,
      duration: 3.1,
      modifiedDuration: 2.7,
      parity: 58.4,
      coupon: 0.75,
      maturityDate: "2030-07-09",
      currency: "USD",
      law: "Local law",
      interpretation: "High carry potential is paired with sovereign risk, restructuring sensitivity and FX premium exposure.",
    },
    news: [
      {
        title: "Sovereign bonds digest FX and reserve expectations",
        source: "Fixed Income Desk",
        sentiment: "negative",
        impact: "high",
        summary: "Mock sovereign-risk context remains the main driver for Argentine dollar bonds.",
      },
    ],
  },
  {
    symbol: "GD30",
    name: "Global 2030",
    type: "sovereign_bond",
    typeLabel: "Sovereign Bond",
    market: "BYMA",
    currency: "USD/ARS",
    price: 61.7,
    dailyChange: 0.28,
    technicalScore: 52,
    riskLevel: "very_high",
    summary: "Global-law Argentine sovereign reference with liquidity and sovereign-risk sensitivity.",
    argentinaContext: true,
    technical: {
      sma20: 60.9,
      sma50: 59.4,
      sma200: 51.2,
      ema12: 61.3,
      ema26: 60.4,
      rsi14: 52.1,
      macd: "Slight positive",
      atr: 1.64,
      bollingerBands: "Middle-upper",
      volumeTrend: "Stable",
      support: 58.2,
      resistance: 64.5,
      signal: "Neutral consolidation",
    },
    bondMetrics: {
      tir: 19.4,
      duration: 3.3,
      modifiedDuration: 2.9,
      parity: 61.7,
      coupon: 0.5,
      maturityDate: "2030-07-09",
      currency: "USD",
      law: "New York law",
      interpretation: "Global-law structure may trade with a different liquidity and legal premium versus local-law bonds.",
    },
    news: [
      {
        title: "Global-law references remain a key market gauge",
        source: "Argentina Credit",
        sentiment: "neutral",
        impact: "high",
        summary: "Mock note frames GD30 as a reference for sovereign risk appetite and hard-dollar liquidity.",
      },
    ],
  },
  {
    symbol: "TX26",
    name: "CER-linked Argentine Treasury Bond",
    type: "cer_bond",
    typeLabel: "CER Bond",
    market: "BYMA",
    currency: "ARS CER",
    price: 142.8,
    dailyChange: 0.74,
    technicalScore: 63,
    riskLevel: "high",
    summary: "Inflation-linked Argentine Treasury exposure tied to CER expectations and peso liquidity.",
    argentinaContext: true,
    technical: {
      sma20: 139.4,
      sma50: 134.1,
      sma200: 118.5,
      ema12: 141.3,
      ema26: 137.8,
      rsi14: 57.2,
      macd: "Positive",
      atr: 2.9,
      bollingerBands: "Upper middle",
      volumeTrend: "Improving",
      support: 136.6,
      resistance: 146.9,
      signal: "Trend confirmation",
    },
    bondMetrics: {
      tir: 6.7,
      duration: 1.5,
      modifiedDuration: 1.4,
      parity: 93.2,
      coupon: 1.45,
      maturityDate: "2026-11-09",
      currency: "ARS CER",
      law: "Local law",
      interpretation: "CER-linked carry can protect against inflation but remains exposed to local curve repricing and liquidity.",
    },
    news: [
      {
        title: "CER curve follows inflation expectation repricing",
        source: "Local Rates",
        sentiment: "positive",
        impact: "medium",
        summary: "Mock local-rates summary highlights demand for inflation-linked instruments.",
      },
    ],
  },
];

const al30 = baseMockAssets.find((asset) => asset.symbol === "AL30");
const gd30 = baseMockAssets.find((asset) => asset.symbol === "GD30");

const bondSpeciesAssets: Asset[] = [
  ...(al30
    ? [
        {
          ...al30,
          symbol: "AL30D",
          name: "Bonar 2030 - Dollar MEP Species",
          currency: "USD",
          price: 58.4,
          summary:
            "Dollar MEP trading species for the Bonar 2030 underlying bond, using mock structured fixed income data.",
        },
        {
          ...al30,
          symbol: "AL30C",
          name: "Bonar 2030 - Dollar Cable Species",
          currency: "USD",
          price: 57.9,
          summary:
            "Dollar cable/CCL trading species for the Bonar 2030 underlying bond, using mock structured fixed income data.",
        },
      ]
    : []),
  ...(gd30
    ? [
        {
          ...gd30,
          symbol: "GD30D",
          name: "Global 2030 - Dollar MEP Species",
          currency: "USD",
          price: 61.7,
          summary:
            "Dollar MEP trading species for the Global 2030 underlying bond, using mock structured fixed income data.",
        },
        {
          ...gd30,
          symbol: "GD30C",
          name: "Global 2030 - Dollar Cable Species",
          currency: "USD",
          price: 61.2,
          summary:
            "Dollar cable/CCL trading species for the Global 2030 underlying bond, using mock structured fixed income data.",
        },
      ]
    : []),
];

export const mockAssets: Asset[] = [...baseMockAssets, ...bondSpeciesAssets];

export const argentinaMarketSymbols = [
  "Merval",
  "GGAL",
  "YPFD",
  "AL30",
  "AL30D",
  "AL30C",
  "GD30",
  "GD30D",
  "GD30C",
  "TX26",
  "CCL reference",
  "MEP reference",
];

export const cryptoMonitorItems = [
  { symbol: "BTC-USD", label: "Bitcoin", value: "$64,280", change: 2.86, context: "Volatility elevated" },
  { symbol: "ETH-USD", label: "Ethereum", value: "$3,184", change: 1.96, context: "Constructive trend" },
  { symbol: "USDT/ARS", label: "Tether Argentina", value: "1,105 ARS", change: 0.92, context: "Crypto dollar reference" },
  { symbol: "DAI/ARS", label: "DAI Argentina", value: "1,099 ARS", change: 0.41, context: "Placeholder pair" },
];

export function findAsset(symbol: string) {
  return mockAssets.find((asset) => asset.symbol.toUpperCase() === symbol.toUpperCase());
}
