import type { Asset, MarketOverviewItem } from "@/types/asset";

export const financialDisclaimer =
  "This platform provides informational analysis only and does not constitute personalized financial advice.";

export const marketOverviewItems: MarketOverviewItem[] = [
  { name: "S&P 500", value: "5,218.42", dailyChange: 0.42, trend: "up", context: "Large-cap breadth improving" },
  { name: "Nasdaq 100", value: "18,142.80", dailyChange: -0.18, trend: "down", context: "Mega-cap tech cooling" },
  { name: "Merval", value: "1,418,220", dailyChange: 1.74, trend: "up", context: "Local equities bid" },
  { name: "Bitcoin", value: "64,280", dailyChange: 2.86, trend: "up", context: "Volatility elevated" },
  { name: "USDT/ARS", value: "1,105", dailyChange: 0.92, trend: "up", context: "Crypto dollar reference" },
  { name: "CCL reference", value: "1,128", dailyChange: -0.34, trend: "down", context: "FX spread watch" },
];

const baseMockAssets: Asset[] = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    type: "stock",
    typeLabel: "Stock",
    market: "NASDAQ",
    currency: "USD",
    price: 191.24,
    dailyChange: 0.84,
    technicalScore: 78,
    fundamentalScore: 82,
    riskLevel: "medium",
    summary: "Quality mega-cap profile with constructive technical recovery and resilient margins.",
    summaryEs: "Compañía tecnológica global de gran capitalización, con ingresos diversificados y exposición relevante a hardware, servicios e inteligencia artificial.",
    technical: {
      sma20: 188.4,
      sma50: 184.2,
      sma200: 179.8,
      ema12: 190.1,
      ema26: 187.2,
      rsi14: 61.4,
      macd: "Positive crossover",
      atr: 3.42,
      bollingerBands: "Upper mid-band",
      volumeTrend: "Accumulation",
      support: 184.6,
      resistance: 196.8,
      signal: "Trend confirmation",
    },
    fundamentals: {
      peRatio: 28.7,
      pbRatio: 39.1,
      roe: 147.3,
      roa: 28.2,
      eps: 6.68,
      ebitdaMargin: 33.6,
      bookValuePerShare: 4.89,
      dividendYield: 0.52,
    },
    news: [
      {
        title: "Services revenue remains a quality driver",
        source: "Market Desk",
        sentiment: "positive",
        impact: "medium",
        summary: "Mock coverage points to durable services contribution and margin stability.",
      },
      {
        title: "Hardware cycle expectations stay measured",
        source: "Equity Monitor",
        sentiment: "neutral",
        impact: "medium",
        summary: "Investors continue to balance replacement-cycle optimism with valuation discipline.",
      },
    ],
  },
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    type: "etf",
    typeLabel: "ETF",
    market: "NYSE Arca",
    currency: "USD",
    price: 521.82,
    dailyChange: 0.38,
    technicalScore: 74,
    fundamentalScore: 70,
    riskLevel: "medium",
    summary: "Broad US equity exposure with stable trend structure and moderate valuation sensitivity.",
    summaryEs: "Exposición amplia a acciones estadounidenses, con estructura de tendencia estable y sensibilidad moderada a valuación.",
    technical: {
      sma20: 518.2,
      sma50: 512.7,
      sma200: 493.4,
      ema12: 520.3,
      ema26: 516.6,
      rsi14: 58.2,
      macd: "Positive",
      atr: 5.76,
      bollingerBands: "Center-upper channel",
      volumeTrend: "Stable",
      support: 511.4,
      resistance: 528.9,
      signal: "Bullish momentum",
    },
    fundamentals: {
      peRatio: 22.1,
      pbRatio: 4.3,
      roe: 19.8,
      roa: 8.7,
      eps: 23.62,
      ebitdaMargin: 22.4,
      bookValuePerShare: 121.2,
      dividendYield: 1.28,
    },
    news: [
      {
        title: "Index breadth improves after mixed macro prints",
        source: "Global Tape",
        sentiment: "positive",
        impact: "medium",
        summary: "Mock breadth indicators show wider participation beyond the largest constituents.",
      },
    ],
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    type: "etf",
    typeLabel: "ETF",
    market: "NASDAQ",
    currency: "USD",
    price: 443.16,
    dailyChange: -0.22,
    technicalScore: 69,
    fundamentalScore: 66,
    riskLevel: "medium",
    summary: "Growth-heavy exposure with strong secular themes and higher rate sensitivity.",
    summaryEs: "Exposición concentrada en crecimiento, con temas seculares sólidos y mayor sensibilidad a tasas.",
    technical: {
      sma20: 445.5,
      sma50: 438.9,
      sma200: 414.7,
      ema12: 442.7,
      ema26: 440.4,
      rsi14: 53.6,
      macd: "Flat positive",
      atr: 6.34,
      bollingerBands: "Middle band",
      volumeTrend: "Neutral",
      support: 432.8,
      resistance: 452.5,
      signal: "Neutral consolidation",
    },
    fundamentals: {
      peRatio: 29.4,
      pbRatio: 7.1,
      roe: 24.5,
      roa: 10.9,
      eps: 15.08,
      ebitdaMargin: 25.2,
      bookValuePerShare: 62.4,
      dividendYield: 0.61,
    },
    news: [
      {
        title: "Technology leadership pauses near highs",
        source: "ETF Radar",
        sentiment: "neutral",
        impact: "medium",
        summary: "Mock flow data suggests investors are waiting for earnings confirmation.",
      },
    ],
  },
  {
    symbol: "GGAL",
    name: "Grupo Financiero Galicia",
    type: "argentine_equity",
    typeLabel: "Argentine Equity / ADR / CEDEAR reference",
    market: "BYMA / NYSE",
    currency: "ARS",
    price: 4360,
    dailyChange: 3.24,
    technicalScore: 83,
    fundamentalScore: 58,
    riskLevel: "very_high",
    summary: "High beta Argentina financial exposure tied to FX expectations and local liquidity.",
    summaryEs: "Entidad financiera argentina con alta sensibilidad al ciclo local, liquidez del mercado y expectativas cambiarias.",
    argentinaContext: true,
    technical: {
      sma20: 4140,
      sma50: 3975,
      sma200: 3180,
      ema12: 4288,
      ema26: 4112,
      rsi14: 68.7,
      macd: "Strong positive",
      atr: 188,
      bollingerBands: "Upper band pressure",
      volumeTrend: "Rising",
      support: 4015,
      resistance: 4620,
      signal: "Breakout watch",
    },
    fundamentals: {
      peRatio: 9.8,
      pbRatio: 1.9,
      roe: 21.4,
      roa: 3.2,
      eps: 445.1,
      ebitdaMargin: 19.6,
      bookValuePerShare: 2294,
      dividendYield: 0.8,
    },
    news: [
      {
        title: "Financials react to local rate expectations",
        source: "Argentina Desk",
        sentiment: "positive",
        impact: "high",
        summary: "Mock market notes highlight sensitivity to policy rates, liquidity and sovereign risk.",
      },
    ],
  },
  {
    symbol: "YPFD",
    name: "YPF S.A.",
    type: "argentine_equity",
    typeLabel: "Argentine Equity / ADR / CEDEAR reference",
    market: "BYMA / NYSE",
    currency: "ARS",
    price: 29750,
    dailyChange: 1.18,
    technicalScore: 72,
    fundamentalScore: 62,
    riskLevel: "high",
    summary: "Energy and Argentina macro exposure with operational upside and policy sensitivity.",
    summaryEs: "Compañía energética argentina con exposición a petróleo, gas, regulación local y expectativas macroeconómicas.",
    argentinaContext: true,
    technical: {
      sma20: 29100,
      sma50: 27820,
      sma200: 23940,
      ema12: 29480,
      ema26: 28610,
      rsi14: 59.8,
      macd: "Positive",
      atr: 980,
      bollingerBands: "Upper middle",
      volumeTrend: "Stable accumulation",
      support: 28150,
      resistance: 30900,
      signal: "Trend confirmation",
    },
    fundamentals: {
      peRatio: 7.4,
      pbRatio: 1.2,
      roe: 16.1,
      roa: 5.4,
      eps: 4018,
      ebitdaMargin: 24.3,
      bookValuePerShare: 24791,
      dividendYield: 0,
    },
    news: [
      {
        title: "Energy names track crude and local regulation",
        source: "Commodities Desk",
        sentiment: "neutral",
        impact: "medium",
        summary: "Mock note flags crude prices, capital expenditure and local pricing rules.",
      },
    ],
  },
  {
    symbol: "BTC-USD",
    name: "Bitcoin",
    type: "crypto",
    typeLabel: "Crypto",
    market: "Crypto",
    currency: "USD",
    price: 64280,
    dailyChange: 2.86,
    technicalScore: 81,
    riskLevel: "very_high",
    summary: "Digital asset benchmark with positive momentum and structurally elevated volatility.",
    summaryEs: "Activo digital de referencia con alta volatilidad y comportamiento sensible a liquidez global y apetito por riesgo.",
    cryptoContext: true,
    technical: {
      sma20: 61750,
      sma50: 59210,
      sma200: 54880,
      ema12: 63420,
      ema26: 61840,
      rsi14: 64.9,
      macd: "Positive expansion",
      atr: 2410,
      bollingerBands: "Upper channel",
      volumeTrend: "Expanding",
      support: 60200,
      resistance: 66800,
      signal: "High volatility",
    },
    news: [
      {
        title: "Crypto volatility remains above traditional assets",
        source: "Crypto Monitor",
        sentiment: "neutral",
        impact: "high",
        summary: "Mock volatility regime points to wider intraday ranges and liquidity-driven moves.",
      },
    ],
  },
  {
    symbol: "ETH-USD",
    name: "Ethereum",
    type: "crypto",
    typeLabel: "Crypto",
    market: "Crypto",
    currency: "USD",
    price: 3184,
    dailyChange: 1.96,
    technicalScore: 76,
    riskLevel: "very_high",
    summary: "Smart-contract platform exposure with constructive trend but high beta to crypto liquidity.",
    summaryEs: "Exposición a plataforma de contratos inteligentes, con tendencia constructiva y alta sensibilidad a la liquidez cripto.",
    cryptoContext: true,
    technical: {
      sma20: 3092,
      sma50: 2970,
      sma200: 2815,
      ema12: 3160,
      ema26: 3088,
      rsi14: 60.7,
      macd: "Positive",
      atr: 154,
      bollingerBands: "Upper middle",
      volumeTrend: "Stable",
      support: 2945,
      resistance: 3320,
      signal: "Bullish momentum",
    },
    news: [
      {
        title: "Network activity holds steady in mock dashboard",
        source: "Crypto Desk",
        sentiment: "positive",
        impact: "medium",
        summary: "Prepared placeholder for future on-chain and market microstructure inputs.",
      },
    ],
  },
  {
    symbol: "AL30",
    name: "Bonar 2030",
    type: "sovereign_bond",
    typeLabel: "Sovereign Bond",
    market: "BYMA",
    currency: "ARS",
    quoteCurrency: "ARS",
    priceDisplayCurrency: "ARS",
    marketDisplayPrice: 58400,
    analyticalPrice: 58.4,
    settlementContext: "Pesos",
    settlementContextEn: "Pesos",
    settlementContextEs: "Pesos",
    marketConventionLabel: "Peso trading species",
    marketConventionLabelEn: "Peso trading species",
    marketConventionLabelEs: "Especie en pesos",
    price: 58400,
    dailyChange: -0.66,
    technicalScore: 44,
    riskLevel: "very_high",
    summary: "Argentine sovereign bond with high yield, high volatility and FX-sensitive price behavior.",
    summaryEs: "Bono soberano argentino utilizado como referencia local, con sensibilidad a riesgo país, tipo de cambio y liquidez.",
    argentinaContext: true,
    technical: {
      sma20: 59.2,
      sma50: 57.7,
      sma200: 49.6,
      ema12: 58.8,
      ema26: 58.1,
      rsi14: 48.8,
      macd: "Neutral",
      atr: 1.82,
      bollingerBands: "Middle band",
      volumeTrend: "Choppy",
      support: 55.6,
      resistance: 61.8,
      signal: "Possible support test",
    },
    bondMetrics: {
      tir: 20.8,
      duration: 3.1,
      modifiedDuration: 2.7,
      parity: 58.4,
      coupon: 0.75,
      maturityDate: "2030-07-09",
      currency: "ARS",
      quoteCurrency: "ARS",
      settlementContext: "Pesos",
      marketDisplayPrice: 58400,
      analyticalPrice: 58.4,
      law: "Local law",
      interpretation: "High carry potential is paired with sovereign risk, restructuring sensitivity and FX premium exposure.",
    },
    news: [
      {
        title: "Sovereign bonds digest FX and reserve expectations",
        source: "Fixed Income Desk",
        sentiment: "negative",
        impact: "high",
        summary: "Mock sovereign-risk context remains the main driver for Argentine dollar bonds.",
      },
    ],
  },
  {
    symbol: "GD30",
    name: "Global 2030",
    type: "sovereign_bond",
    typeLabel: "Sovereign Bond",
    market: "BYMA",
    currency: "ARS",
    quoteCurrency: "ARS",
    priceDisplayCurrency: "ARS",
    marketDisplayPrice: 92300,
    analyticalPrice: 61.7,
    settlementContext: "Pesos",
    settlementContextEn: "Pesos",
    settlementContextEs: "Pesos",
    marketConventionLabel: "Peso trading species",
    marketConventionLabelEn: "Peso trading species",
    marketConventionLabelEs: "Especie en pesos",
    price: 92300,
    dailyChange: 0.28,
    technicalScore: 52,
    riskLevel: "very_high",
    summary: "Global-law Argentine sovereign reference with liquidity and sovereign-risk sensitivity.",
    summaryEs: "Referencia soberana argentina bajo ley extranjera, sensible a liquidez, riesgo país y valuación relativa frente a bonos de ley local.",
    argentinaContext: true,
    technical: {
      sma20: 60.9,
      sma50: 59.4,
      sma200: 51.2,
      ema12: 61.3,
      ema26: 60.4,
      rsi14: 52.1,
      macd: "Slight positive",
      atr: 1.64,
      bollingerBands: "Middle-upper",
      volumeTrend: "Stable",
      support: 58.2,
      resistance: 64.5,
      signal: "Neutral consolidation",
    },
    bondMetrics: {
      tir: 19.4,
      duration: 3.3,
      modifiedDuration: 2.9,
      parity: 61.7,
      coupon: 0.5,
      maturityDate: "2030-07-09",
      currency: "ARS",
      quoteCurrency: "ARS",
      settlementContext: "Pesos",
      marketDisplayPrice: 92300,
      analyticalPrice: 61.7,
      law: "New York law",
      interpretation: "Global-law structure may trade with a different liquidity and legal premium versus local-law bonds.",
    },
    news: [
      {
        title: "Global-law references remain a key market gauge",
        source: "Argentina Credit",
        sentiment: "neutral",
        impact: "high",
        summary: "Mock note frames GD30 as a reference for sovereign risk appetite and hard-dollar liquidity.",
      },
    ],
  },
  {
    symbol: "TX26",
    name: "CER-linked Argentine Treasury bond",
    nameEs: "Bono del Tesoro argentino ajustado por CER",
    type: "cer_bond",
    typeLabel: "CER Bond",
    market: "BYMA",
    currency: "ARS",
    quoteCurrency: "ARS",
    priceDisplayCurrency: "ARS",
    marketDisplayPrice: 142.8,
    analyticalPrice: 142.8,
    settlementContext: "CER-linked / ARS",
    settlementContextEn: "CER-linked / ARS",
    settlementContextEs: "Pesos ajustados por CER",
    indexationType: "CER",
    marketConventionLabel: "CER-linked ARS bond",
    marketConventionLabelEn: "CER-linked ARS bond",
    marketConventionLabelEs: "Bono CER",
    price: 142.8,
    dailyChange: 0.74,
    technicalScore: 63,
    riskLevel: "high",
    summary: "Inflation-linked Argentine Treasury exposure tied to CER expectations and peso liquidity.",
    summaryEs: "Bono del Tesoro argentino ajustado por CER, sensible a expectativas de inflación, tasas reales y liquidez en pesos.",
    argentinaContext: true,
    technical: {
      sma20: 139.4,
      sma50: 134.1,
      sma200: 118.5,
      ema12: 141.3,
      ema26: 137.8,
      rsi14: 57.2,
      macd: "Positive",
      atr: 2.9,
      bollingerBands: "Upper middle",
      volumeTrend: "Improving",
      support: 136.6,
      resistance: 146.9,
      signal: "Trend confirmation",
    },
    bondMetrics: {
      tir: 6.7,
      duration: 1.5,
      modifiedDuration: 1.4,
      parity: 93.2,
      coupon: 1.45,
      maturityDate: "2026-11-09",
      currency: "ARS",
      quoteCurrency: "ARS",
      settlementContext: "Pesos ajustados por CER",
      indexationType: "CER",
      marketDisplayPrice: 142.8,
      analyticalPrice: 142.8,
      law: "Local law",
      interpretation: "CER-linked carry can protect against inflation but remains exposed to local curve repricing and liquidity.",
    },
    news: [
      {
        title: "CER curve follows inflation expectation repricing",
        source: "Local Rates",
        sentiment: "positive",
        impact: "medium",
        summary: "Mock local-rates summary highlights demand for inflation-linked instruments.",
      },
    ],
  },
];

const al30 = baseMockAssets.find((asset) => asset.symbol === "AL30");
const gd30 = baseMockAssets.find((asset) => asset.symbol === "GD30");

const bondSpeciesAssets: Asset[] = [
  ...(al30
    ? [
        {
          ...al30,
          symbol: "AL30D",
          name: "Bonar 2030 - Dollar MEP species",
          nameEs: "Bonar 2030 - Especie dólar MEP",
          currency: "USD",
          quoteCurrency: "USD",
          priceDisplayCurrency: "USD",
          marketDisplayPrice: 58.4,
          analyticalPrice: 58.4,
          settlementContext: "Dollar MEP",
          settlementContextEn: "Dollar MEP",
          settlementContextEs: "Dólar MEP",
          marketConventionLabel: "Dollar MEP species",
          marketConventionLabelEn: "Dollar MEP species",
          marketConventionLabelEs: "Especie dólar MEP",
          price: 58.4,
          bondMetrics: al30.bondMetrics ? { ...al30.bondMetrics, currency: "USD", quoteCurrency: "USD", settlementContext: "Dólar MEP", marketDisplayPrice: 58.4, analyticalPrice: 58.4 } : undefined,
          summary:
            "Dollar MEP trading species for the Bonar 2030 underlying bond, using mock structured fixed income data.",
          summaryEs: "Especie dólar MEP del Bonar 2030, con precio simulado en USD y métricas normalizadas de renta fija.",
        },
        {
          ...al30,
          symbol: "AL30C",
          name: "Bonar 2030 - Dollar cable/CCL species",
          nameEs: "Bonar 2030 - Especie dólar cable/CCL",
          currency: "USD",
          quoteCurrency: "USD",
          priceDisplayCurrency: "USD",
          marketDisplayPrice: 57.9,
          analyticalPrice: 57.9,
          settlementContext: "Dollar cable/CCL",
          settlementContextEn: "Dollar cable/CCL",
          settlementContextEs: "Dólar cable/CCL",
          marketConventionLabel: "Dollar cable/CCL species",
          marketConventionLabelEn: "Dollar cable/CCL species",
          marketConventionLabelEs: "Especie dólar cable/CCL",
          price: 57.9,
          bondMetrics: al30.bondMetrics ? { ...al30.bondMetrics, currency: "USD", quoteCurrency: "USD", settlementContext: "Dólar cable/CCL", marketDisplayPrice: 57.9, analyticalPrice: 57.9 } : undefined,
          summary:
            "Dollar cable/CCL trading species for the Bonar 2030 underlying bond, using mock structured fixed income data.",
          summaryEs: "Especie dólar cable/CCL del Bonar 2030, con precio simulado en USD y métricas normalizadas de renta fija.",
        },
      ]
    : []),
  ...(gd30
    ? [
        {
          ...gd30,
          symbol: "GD30D",
          name: "Global 2030 - Dollar MEP species",
          nameEs: "Global 2030 - Especie dólar MEP",
          currency: "USD",
          quoteCurrency: "USD",
          priceDisplayCurrency: "USD",
          marketDisplayPrice: 61.7,
          analyticalPrice: 61.7,
          settlementContext: "Dollar MEP",
          settlementContextEn: "Dollar MEP",
          settlementContextEs: "Dólar MEP",
          marketConventionLabel: "Dollar MEP species",
          marketConventionLabelEn: "Dollar MEP species",
          marketConventionLabelEs: "Especie dólar MEP",
          price: 61.7,
          bondMetrics: gd30.bondMetrics ? { ...gd30.bondMetrics, currency: "USD", quoteCurrency: "USD", settlementContext: "Dólar MEP", marketDisplayPrice: 61.7, analyticalPrice: 61.7 } : undefined,
          summary:
            "Dollar MEP trading species for the Global 2030 underlying bond, using mock structured fixed income data.",
          summaryEs: "Especie dólar MEP del Global 2030, con precio simulado en USD y métricas normalizadas de renta fija.",
        },
        {
          ...gd30,
          symbol: "GD30C",
          name: "Global 2030 - Dollar cable/CCL species",
          nameEs: "Global 2030 - Especie dólar cable/CCL",
          currency: "USD",
          quoteCurrency: "USD",
          priceDisplayCurrency: "USD",
          marketDisplayPrice: 61.2,
          analyticalPrice: 61.2,
          settlementContext: "Dollar cable/CCL",
          settlementContextEn: "Dollar cable/CCL",
          settlementContextEs: "Dólar cable/CCL",
          marketConventionLabel: "Dollar cable/CCL species",
          marketConventionLabelEn: "Dollar cable/CCL species",
          marketConventionLabelEs: "Especie dólar cable/CCL",
          price: 61.2,
          bondMetrics: gd30.bondMetrics ? { ...gd30.bondMetrics, currency: "USD", quoteCurrency: "USD", settlementContext: "Dólar cable/CCL", marketDisplayPrice: 61.2, analyticalPrice: 61.2 } : undefined,
          summary:
            "Dollar cable/CCL trading species for the Global 2030 underlying bond, using mock structured fixed income data.",
          summaryEs: "Especie dólar cable/CCL del Global 2030, con precio simulado en USD y métricas normalizadas de renta fija.",
        },
      ]
    : []),
];

const expandedUsAssets: Asset[] = [
  ["MSFT", "Microsoft Corporation", 427.8, 0.62, 76, 80, "Enterprise software and cloud platform exposure with provider chart coverage and fallback fundamentals."],
  ["NVDA", "NVIDIA Corporation", 913.4, 1.34, 84, 78, "AI semiconductor leader with high momentum and valuation sensitivity."],
  ["TSLA", "Tesla Inc.", 182.2, -0.48, 61, 54, "High-volatility growth exposure tied to EV demand, margins and execution risk."],
  ["AMZN", "Amazon.com Inc.", 186.9, 0.71, 73, 72, "Large-cap commerce and cloud profile with provider market data and fallback-safe analysis."],
  ["META", "Meta Platforms Inc.", 489.1, 0.52, 75, 76, "Advertising and AI infrastructure exposure with constructive mock/fallback scoring."],
  ["GOOGL", "Alphabet Inc.", 171.3, 0.39, 70, 74, "Search, cloud and AI platform exposure with provider market data attempts."],
  ["KO", "The Coca-Cola Company", 62.4, 0.18, 58, 68, "Defensive consumer staples exposure with dividend and beta context prepared for provider fundamentals."],
].map(([symbol, name, price, dailyChange, technicalScore, fundamentalScore, summary]) => ({
  symbol: symbol as string,
  name: name as string,
  type: "stock" as const,
  typeLabel: "Stock",
  market: symbol === "KO" ? "NYSE" : "NASDAQ",
  currency: "USD",
  price: price as number,
  dailyChange: dailyChange as number,
  technicalScore: technicalScore as number,
  fundamentalScore: fundamentalScore as number,
  riskLevel: symbol === "TSLA" || symbol === "NVDA" ? "high" as const : "medium" as const,
  summary: summary as string,
  summaryEs: "Acción estadounidense con intentos de datos de proveedor público y análisis de respaldo para preservar la experiencia de demo.",
  technical: {
    sma20: (price as number) * 0.98,
    sma50: (price as number) * 0.95,
    sma200: (price as number) * 0.88,
    ema12: (price as number) * 0.99,
    ema26: (price as number) * 0.96,
    rsi14: technicalScore as number,
    macd: (technicalScore as number) >= 65 ? "Positive" : "Neutral",
    atr: (price as number) * 0.025,
    bollingerBands: "Middle-upper channel",
    volumeTrend: "Provider/fallback dependent",
    support: (price as number) * 0.92,
    resistance: (price as number) * 1.08,
    signal: (technicalScore as number) >= 70 ? "Trend confirmation" : "Neutral consolidation",
  },
  fundamentals: {
    peRatio: symbol === "KO" ? 23.4 : 30.2,
    pbRatio: symbol === "NVDA" ? 24.5 : 8.4,
    roe: symbol === "KO" ? 38.2 : 29.6,
    roa: symbol === "KO" ? 10.4 : 15.1,
    eps: (price as number) / (symbol === "KO" ? 23.4 : 30.2),
    ebitdaMargin: symbol === "TSLA" ? 14.8 : 28.6,
    bookValuePerShare: (price as number) / (symbol === "NVDA" ? 24.5 : 8.4),
    dividendYield: symbol === "KO" ? 3.1 : 0.4,
  },
  news: [
    {
      title: "Provider coverage prepared with fallback analytics",
      source: "Market Desk",
      sentiment: "neutral" as const,
      impact: "medium" as const,
      summary: "Public provider data is attempted where available; fallback mock analytics preserve the demo experience.",
    },
  ],
}));

const expandedCryptoAssets: Asset[] = [
  ["BNB-USD", "BNB", 585, 1.1, 66],
  ["SOL-USD", "Solana", 148, 2.4, 72],
  ["XRP-USD", "XRP", 0.58, 0.7, 54],
  ["ADA-USD", "Cardano", 0.46, -0.3, 49],
  ["DOGE-USD", "Dogecoin", 0.15, 1.8, 57],
  ["AVAX-USD", "Avalanche", 37, 1.5, 62],
  ["LINK-USD", "Chainlink", 16.8, 0.9, 60],
  ["DOT-USD", "Polkadot", 7.2, 0.4, 52],
].map(([symbol, name, price, dailyChange, technicalScore]) => ({
  symbol: symbol as string,
  name: name as string,
  type: "crypto" as const,
  typeLabel: "Crypto",
  market: "Crypto",
  currency: "USD",
  price: price as number,
  dailyChange: dailyChange as number,
  technicalScore: technicalScore as number,
  riskLevel: "very_high" as const,
  summary: "Crypto asset with public provider data attempts and fallback OHLCV analytics for the demo.",
  summaryEs: "Criptoactivo con intentos de datos de proveedor público y análisis OHLCV de respaldo para la demo.",
  cryptoContext: true,
  technical: {
    sma20: (price as number) * 0.97,
    sma50: (price as number) * 0.93,
    sma200: (price as number) * 0.82,
    ema12: (price as number) * 0.98,
    ema26: (price as number) * 0.94,
    rsi14: technicalScore as number,
    macd: (technicalScore as number) >= 60 ? "Positive" : "Neutral",
    atr: (price as number) * 0.08,
    bollingerBands: "Volatile channel",
    volumeTrend: "Exchange dependent",
    support: (price as number) * 0.88,
    resistance: (price as number) * 1.14,
    signal: "High volatility",
  },
  news: [
    {
      title: "Crypto provider coverage expanded",
      source: "Crypto Monitor",
      sentiment: "neutral" as const,
      impact: "medium" as const,
      summary: "Public exchange data is attempted without API keys; fallback behavior remains active.",
    },
  ],
}));

export const mockAssets: Asset[] = [...baseMockAssets, ...bondSpeciesAssets, ...expandedUsAssets, ...expandedCryptoAssets];

export const argentinaMarketSymbols = [
  "Merval",
  "GGAL",
  "YPFD",
  "AL30",
  "AL30D",
  "AL30C",
  "GD30",
  "GD30D",
  "GD30C",
  "TX26",
  "CCL reference",
  "MEP reference",
];

export const cryptoMonitorItems = [
  { symbol: "BTC-USD", label: "Bitcoin", value: "$64,280", change: 2.86, context: "Volatility elevated" },
  { symbol: "ETH-USD", label: "Ethereum", value: "$3,184", change: 1.96, context: "Constructive trend" },
  { symbol: "USDT/ARS", label: "Tether Argentina", value: "1,105 ARS", change: 0.92, context: "Crypto dollar reference" },
  { symbol: "DAI/ARS", label: "DAI Argentina", value: "1,099 ARS", change: 0.41, context: "Placeholder pair" },
];

export function findAsset(symbol: string) {
  return mockAssets.find((asset) => asset.symbol.toUpperCase() === symbol.toUpperCase());
}
