import type { GlossaryTerm, GlossaryTermKey } from "./types";

const standaloneCaution = {
  cautionEn: "Should not be used as a standalone signal.",
  cautionEs: "No debe utilizarse como señal aislada.",
};

export const glossaryTerms: Record<GlossaryTermKey, GlossaryTerm> = {
  trend: {
    key: "trend",
    labelEn: "Trend",
    labelEs: "Tendencia",
    shortDefinitionEn: "General direction of price behavior over the selected period.",
    shortDefinitionEs: "Dirección general del comportamiento del precio en el período seleccionado.",
    category: "technical",
    ...standaloneCaution,
  },
  momentum: {
    key: "momentum",
    labelEn: "Momentum",
    labelEs: "Momentum",
    shortDefinitionEn: "Measures the speed and strength of recent price movement.",
    shortDefinitionEs: "Mide la velocidad y fuerza del movimiento reciente del precio.",
    category: "technical",
    ...standaloneCaution,
  },
  sma20: {
    key: "sma20",
    labelEn: "SMA 20",
    labelEs: "SMA 20",
    shortDefinitionEn: "Simple average of the last 20 closes, used for short-term trend context.",
    shortDefinitionEs: "Promedio simple de los últimos 20 cierres, usado como referencia de tendencia de corto plazo.",
    formula: "SMA = sum(closes) / periods",
    category: "technical",
  },
  sma50: {
    key: "sma50",
    labelEn: "SMA 50",
    labelEs: "SMA 50",
    shortDefinitionEn: "Simple average of the last 50 closes, commonly used for medium-term trend context.",
    shortDefinitionEs: "Promedio simple de los últimos 50 cierres, usado para contexto de tendencia de mediano plazo.",
    formula: "SMA = sum(closes) / periods",
    category: "technical",
  },
  sma200: {
    key: "sma200",
    labelEn: "SMA 200",
    labelEs: "SMA 200",
    shortDefinitionEn: "Long-term simple moving average often used to identify broad trend regime.",
    shortDefinitionEs: "Media móvil simple de largo plazo usada para identificar el régimen general de tendencia.",
    formula: "SMA = sum(closes) / periods",
    category: "technical",
  },
  ema12: {
    key: "ema12",
    labelEn: "EMA 12",
    labelEs: "EMA 12",
    shortDefinitionEn: "Exponential moving average that gives more weight to recent prices.",
    shortDefinitionEs: "Media móvil exponencial que da más peso a los precios recientes.",
    category: "technical",
  },
  ema26: {
    key: "ema26",
    labelEn: "EMA 26",
    labelEs: "EMA 26",
    shortDefinitionEn: "Slower exponential moving average frequently used in MACD calculations.",
    shortDefinitionEs: "Media móvil exponencial más lenta, usada frecuentemente en el cálculo de MACD.",
    category: "technical",
  },
  rsi14: {
    key: "rsi14",
    labelEn: "RSI 14",
    labelEs: "RSI 14",
    shortDefinitionEn: "Momentum oscillator from 0 to 100. Very high readings may suggest overbought conditions and very low readings may suggest oversold conditions.",
    shortDefinitionEs: "Indicador de momentum que oscila entre 0 y 100. Lecturas muy altas pueden sugerir sobrecompra y lecturas muy bajas pueden sugerir sobreventa.",
    category: "technical",
    ...standaloneCaution,
  },
  macd: {
    key: "macd",
    labelEn: "MACD",
    labelEs: "MACD",
    shortDefinitionEn: "Trend and momentum indicator based on the difference between fast and slow EMAs.",
    shortDefinitionEs: "Indicador de tendencia y momentum basado en la diferencia entre EMAs rápida y lenta.",
    formula: "MACD = EMA 12 - EMA 26",
    category: "technical",
  },
  macdSignal: {
    key: "macdSignal",
    labelEn: "MACD Signal",
    labelEs: "Señal MACD",
    shortDefinitionEn: "Moving average of the MACD line used as a comparison line.",
    shortDefinitionEs: "Media móvil de la línea MACD usada como línea de comparación.",
    category: "technical",
  },
  macdHistogram: {
    key: "macdHistogram",
    labelEn: "MACD Histogram",
    labelEs: "Histograma MACD",
    shortDefinitionEn: "Difference between MACD and its signal line.",
    shortDefinitionEs: "Diferencia entre el MACD y su linea de señal.",
    formula: "Histogram = MACD - signal",
    category: "technical",
  },
  support: {
    key: "support",
    labelEn: "Support",
    labelEs: "Soporte",
    shortDefinitionEn: "Recent price area where demand has previously appeared.",
    shortDefinitionEs: "Zona reciente de precio donde previamente apareció demanda.",
    category: "technical",
    ...standaloneCaution,
  },
  resistance: {
    key: "resistance",
    labelEn: "Resistance",
    labelEs: "Resistencia",
    shortDefinitionEn: "Recent price area where supply has previously appeared.",
    shortDefinitionEs: "Zona reciente de precio donde previamente apareció oferta.",
    category: "technical",
    ...standaloneCaution,
  },
  volumeTrend: {
    key: "volumeTrend",
    labelEn: "Volume trend",
    labelEs: "Tendencia de volumen",
    shortDefinitionEn: "Compares recent trading volume with prior volume to estimate participation.",
    shortDefinitionEs: "Compara el volumen reciente con el volumen previo para estimar participación.",
    category: "technical",
  },
  pe: {
    key: "pe",
    labelEn: "P/E",
    labelEs: "P/E",
    shortDefinitionEn: "Relates market price to earnings per share as a valuation reference.",
    shortDefinitionEs: "Relaciona el precio de mercado con la ganancia por acción como referencia de valuación.",
    formula: "P/E = price / EPS",
    category: "fundamentals",
  },
  forwardPe: {
    key: "forwardPe",
    labelEn: "Forward P/E",
    labelEs: "P/E proyectado",
    shortDefinitionEn: "Valuation ratio using expected future earnings instead of trailing earnings.",
    shortDefinitionEs: "Ratio de valuación que usa ganancias esperadas futuras en lugar de ganancias históricas.",
    category: "fundamentals",
  },
  pb: {
    key: "pb",
    labelEn: "P/B",
    labelEs: "P/B",
    shortDefinitionEn: "Compares market price with book value per share.",
    shortDefinitionEs: "Compara el precio de mercado con el valor libro por acción.",
    formula: "P/B = price / book value per share",
    category: "fundamentals",
  },
  ps: {
    key: "ps",
    labelEn: "P/S",
    labelEs: "P/S",
    shortDefinitionEn: "Compares market value with sales or revenue.",
    shortDefinitionEs: "Compara el valor de mercado con ventas o ingresos.",
    category: "fundamentals",
  },
  peg: {
    key: "peg",
    labelEn: "PEG",
    labelEs: "PEG",
    shortDefinitionEn: "Relates valuation to expected earnings growth.",
    shortDefinitionEs: "Relaciona la valuación con el crecimiento esperado de ganancias.",
    category: "fundamentals",
  },
  eps: {
    key: "eps",
    labelEn: "EPS",
    labelEs: "BPA",
    shortDefinitionEn: "Earnings allocated to each share.",
    shortDefinitionEs: "Ganancia atribuible a cada acción.",
    formula: "EPS = net income / shares",
    category: "fundamentals",
  },
  bookValuePerShare: {
    key: "bookValuePerShare",
    labelEn: "Book value/share",
    labelEs: "Valor libro/acción",
    shortDefinitionEn: "Accounting equity value allocated to each share.",
    shortDefinitionEs: "Valor contable del patrimonio atribuido a cada acción.",
    category: "fundamentals",
  },
  roe: {
    key: "roe",
    labelEn: "ROE",
    labelEs: "ROE",
    shortDefinitionEn: "Measures profitability generated on shareholders' equity.",
    shortDefinitionEs: "Mide la rentabilidad generada sobre el patrimonio neto.",
    formula: "ROE = net income / equity",
    category: "fundamentals",
    cautionEn: "A high ROE should be reviewed with leverage, sector and sustainability.",
    cautionEs: "Un ROE alto debe analizarse junto con deuda, sector y sostenibilidad.",
  },
  roa: {
    key: "roa",
    labelEn: "ROA",
    labelEs: "ROA",
    shortDefinitionEn: "Measures profit generated relative to total assets.",
    shortDefinitionEs: "Mide la ganancia generada en relación con los activos totales.",
    formula: "ROA = net income / total assets",
    category: "fundamentals",
  },
  grossMargin: {
    key: "grossMargin",
    labelEn: "Gross margin",
    labelEs: "Margen bruto",
    shortDefinitionEn: "Revenue left after direct cost of goods or services.",
    shortDefinitionEs: "Ingresos que quedan luego del costo directo de bienes o servicios.",
    category: "fundamentals",
  },
  operatingMargin: {
    key: "operatingMargin",
    labelEn: "Operating margin",
    labelEs: "Margen operativo",
    shortDefinitionEn: "Operating profit as a percentage of revenue.",
    shortDefinitionEs: "Resultado operativo como porcentaje de ingresos.",
    category: "fundamentals",
  },
  ebitdaMargin: {
    key: "ebitdaMargin",
    labelEn: "EBITDA margin",
    labelEs: "Margen EBITDA",
    shortDefinitionEn: "EBITDA as a percentage of revenue.",
    shortDefinitionEs: "EBITDA como porcentaje de ingresos.",
    category: "fundamentals",
  },
  netMargin: {
    key: "netMargin",
    labelEn: "Net margin",
    labelEs: "Margen neto",
    shortDefinitionEn: "Net income as a percentage of revenue.",
    shortDefinitionEs: "Ganancia neta como porcentaje de ingresos.",
    category: "fundamentals",
  },
  revenueGrowth: {
    key: "revenueGrowth",
    labelEn: "Revenue growth",
    labelEs: "Crecimiento de ingresos",
    shortDefinitionEn: "Change in revenue versus a prior comparable period.",
    shortDefinitionEs: "Variación de ingresos frente a un período comparable anterior.",
    category: "fundamentals",
  },
  earningsGrowth: {
    key: "earningsGrowth",
    labelEn: "Earnings growth",
    labelEs: "Crecimiento de ganancias",
    shortDefinitionEn: "Change in earnings versus a prior comparable period.",
    shortDefinitionEs: "Variación de ganancias frente a un período comparable anterior.",
    category: "fundamentals",
  },
  debtToEquity: {
    key: "debtToEquity",
    labelEn: "Debt/equity",
    labelEs: "Deuda/patrimonio",
    shortDefinitionEn: "Compares debt with shareholders' equity.",
    shortDefinitionEs: "Compara la deuda con el patrimonio neto.",
    category: "fundamentals",
  },
  currentRatio: {
    key: "currentRatio",
    labelEn: "Current ratio",
    labelEs: "Ratio corriente",
    shortDefinitionEn: "Short-term liquidity ratio comparing current assets with current liabilities.",
    shortDefinitionEs: "Ratio de liquidez de corto plazo que compara activos corrientes con pasivos corrientes.",
    category: "fundamentals",
  },
  quickRatio: {
    key: "quickRatio",
    labelEn: "Quick ratio",
    labelEs: "Ratio rápido",
    shortDefinitionEn: "Liquidity ratio excluding inventories from current assets.",
    shortDefinitionEs: "Ratio de liquidez que excluye inventarios de los activos corrientes.",
    category: "fundamentals",
  },
  dividendYield: {
    key: "dividendYield",
    labelEn: "Dividend yield",
    labelEs: "Rendimiento por dividendos",
    shortDefinitionEn: "Annual dividends as a percentage of market price.",
    shortDefinitionEs: "Dividendos anuales como porcentaje del precio de mercado.",
    category: "fundamentals",
  },
  beta: {
    key: "beta",
    labelEn: "Beta",
    labelEs: "Beta",
    shortDefinitionEn: "Measures sensitivity versus a market benchmark.",
    shortDefinitionEs: "Mide sensibilidad frente a un benchmark de mercado.",
    category: "risk",
  },
  fiftyTwoWeekHigh: {
    key: "fiftyTwoWeekHigh",
    labelEn: "52W High",
    labelEs: "Máximo 52 semanas",
    shortDefinitionEn: "Highest traded price in the last 52 weeks.",
    shortDefinitionEs: "Precio máximo operado en las últimas 52 semanas.",
    category: "market",
  },
  fiftyTwoWeekLow: {
    key: "fiftyTwoWeekLow",
    labelEn: "52W Low",
    labelEs: "Mínimo 52 semanas",
    shortDefinitionEn: "Lowest traded price in the last 52 weeks.",
    shortDefinitionEs: "Precio mínimo operado en las últimas 52 semanas.",
    category: "market",
  },
  marketCap: {
    key: "marketCap",
    labelEn: "Market cap",
    labelEs: "Capitalizacion bursatil",
    shortDefinitionEn: "Estimated market value of all outstanding shares.",
    shortDefinitionEs: "Valor de mercado estimado de todas las acciones en circulación.",
    category: "market",
  },
  ytm: {
    key: "ytm",
    labelEn: "YTM",
    labelEs: "TIR",
    shortDefinitionEn: "Estimated annual return if cash flows are held to maturity and assumptions hold.",
    shortDefinitionEs: "Retorno anual estimado si los flujos se mantienen hasta vencimiento y se cumplen los supuestos.",
    category: "fixed_income",
    cautionEn: "Higher yield can reflect higher risk.",
    cautionEs: "Una TIR más alta puede reflejar mayor riesgo.",
  },
  tir: {
    key: "tir",
    labelEn: "TIR",
    labelEs: "TIR",
    shortDefinitionEn: "Spanish market term for yield to maturity.",
    shortDefinitionEs: "Tasa interna de retorno estimada de un bono hasta vencimiento.",
    category: "fixed_income",
  },
  currentYield: {
    key: "currentYield",
    labelEn: "Current yield",
    labelEs: "Rendimiento corriente",
    shortDefinitionEn: "Annual coupon income divided by current market price.",
    shortDefinitionEs: "Cupón anual dividido por el precio de mercado actual.",
    formula: "Current yield = annual coupon / price",
    category: "fixed_income",
  },
  parity: {
    key: "parity",
    labelEn: "Parity",
    labelEs: "Paridad",
    shortDefinitionEn: "Bond price relative to face value.",
    shortDefinitionEs: "Precio del bono en relación con su valor nominal.",
    formula: "Parity = price / face value",
    category: "fixed_income",
  },
  duration: {
    key: "duration",
    labelEn: "Duration",
    labelEs: "Duration",
    shortDefinitionEn: "Approximate timing and interest-rate sensitivity of bond cash flows.",
    shortDefinitionEs: "Mide la sensibilidad aproximada del precio de un bono ante cambios en la tasa de interés.",
    category: "fixed_income",
  },
  modifiedDuration: {
    key: "modifiedDuration",
    labelEn: "Modified duration",
    labelEs: "Duration modificada",
    shortDefinitionEn: "Approximate percentage price sensitivity to a change in yield.",
    shortDefinitionEs: "Sensibilidad porcentual aproximada del precio ante cambios en la tasa.",
    category: "fixed_income",
  },
  convexity: {
    key: "convexity",
    labelEn: "Convexity",
    labelEs: "Convexity",
    shortDefinitionEn: "Approximation of the curvature in the price-yield relationship.",
    shortDefinitionEs: "Aproximación de la curvatura en la relación precio-tasa.",
    category: "fixed_income",
  },
  accruedInterest: {
    key: "accruedInterest",
    labelEn: "Accrued interest",
    labelEs: "Intereses corridos",
    shortDefinitionEn: "Coupon interest earned since the last coupon date.",
    shortDefinitionEs: "Interés del cupón acumulado desde la última fecha de pago.",
    category: "fixed_income",
  },
  cleanPrice: {
    key: "cleanPrice",
    labelEn: "Clean price",
    labelEs: "Precio limpio",
    shortDefinitionEn: "Bond price excluding accrued interest.",
    shortDefinitionEs: "Precio del bono sin intereses corridos.",
    category: "fixed_income",
  },
  dirtyPrice: {
    key: "dirtyPrice",
    labelEn: "Dirty price",
    labelEs: "Precio sucio",
    shortDefinitionEn: "Bond price including accrued interest.",
    shortDefinitionEs: "Precio del bono incluyendo intereses corridos.",
    category: "fixed_income",
  },
  coupon: {
    key: "coupon",
    labelEn: "Coupon",
    labelEs: "Cupón",
    shortDefinitionEn: "Periodic interest paid by a bond under its terms.",
    shortDefinitionEs: "Interés periódico que paga un bono según sus condiciones.",
    category: "fixed_income",
  },
  maturityDate: {
    key: "maturityDate",
    labelEn: "Maturity date",
    labelEs: "Vencimiento",
    shortDefinitionEn: "Date when the bond principal is due.",
    shortDefinitionEs: "Fecha en la que vence el capital del bono.",
    category: "fixed_income",
  },
  law: {
    key: "law",
    labelEn: "Law",
    labelEs: "Ley",
    shortDefinitionEn: "Legal jurisdiction governing the instrument.",
    shortDefinitionEs: "Jurisdiccion legal que rige el instrumento.",
    category: "fixed_income",
  },
  cer: {
    key: "cer",
    labelEn: "CER",
    labelEs: "CER",
    shortDefinitionEn: "Argentina inflation index adjustment reference.",
    shortDefinitionEs: "Referencia de ajuste por inflación en Argentina.",
    category: "fixed_income",
  },
  dollarLinked: {
    key: "dollarLinked",
    labelEn: "Dollar-linked",
    labelEs: "Dollar-linked",
    shortDefinitionEn: "Instrument whose payoff is linked to an exchange-rate reference.",
    shortDefinitionEs: "Instrumento cuyo repago esta vinculado a una referencia de tipo de cambio.",
    category: "fixed_income",
  },
  cedear: {
    key: "cedear",
    labelEn: "CEDEAR",
    labelEs: "CEDEAR",
    shortDefinitionEn: "Argentine local instrument linked to an international stock or ETF.",
    shortDefinitionEs: "Instrumento local argentino vinculado a una acción o ETF internacional.",
    category: "cedears",
  },
  underlyingAsset: {
    key: "underlyingAsset",
    labelEn: "Underlying asset",
    labelEs: "Activo subyacente",
    shortDefinitionEn: "International asset that the local CEDEAR economically references.",
    shortDefinitionEs: "Activo internacional al que referencia económicamente el CEDEAR local.",
    category: "cedears",
  },
  cedearRatio: {
    key: "cedearRatio",
    labelEn: "CEDEAR ratio",
    labelEs: "Ratio CEDEAR",
    shortDefinitionEn: "Number of CEDEARs equivalent to one underlying share under the chosen convention.",
    shortDefinitionEs: "Cantidad de CEDEARs equivalentes a una acción subyacente bajo la convención elegida.",
    category: "cedears",
  },
  impliedCcl: {
    key: "impliedCcl",
    labelEn: "Implied CCL",
    labelEs: "CCL implícito",
    shortDefinitionEn: "Exchange-rate reference inferred from local CEDEAR price, ratio and underlying USD price.",
    shortDefinitionEs: "Referencia de tipo de cambio inferida desde precio local del CEDEAR, ratio y precio USD del subyacente.",
    formula: "Implied CCL = local CEDEAR ARS price * ratio / underlying USD price",
    category: "cedears",
  },
  dollarMep: {
    key: "dollarMep",
    labelEn: "Dollar MEP",
    labelEs: "Dólar MEP",
    shortDefinitionEn: "Local securities-based dollar reference settled in Argentina.",
    shortDefinitionEs: "Referencia de dólar financiero local liquidado en Argentina.",
    category: "market",
  },
  cableCclDollar: {
    key: "cableCclDollar",
    labelEn: "Cable/CCL dollar",
    labelEs: "Dólar cable/CCL",
    shortDefinitionEn: "Securities-based dollar reference associated with offshore settlement context.",
    shortDefinitionEs: "Referencia de dólar financiero asociada a liquidación en el exterior.",
    category: "market",
  },
  arbitrageSpread: {
    key: "arbitrageSpread",
    labelEn: "Arbitrage spread",
    labelEs: "Spread de arbitraje",
    shortDefinitionEn: "Difference between an implied market reference and a comparison benchmark.",
    shortDefinitionEs: "Diferencia entre una referencia implícita de mercado y un benchmark de comparación.",
    formula: "Spread = implied reference / benchmark - 1",
    category: "market",
  },
  executiveReading: {
    key: "executiveReading",
    labelEn: "Executive reading",
    labelEs: "Lectura ejecutiva",
    shortDefinitionEn: "Concise non-advisory synthesis of price, technicals, fundamentals, news, risks and data coverage.",
    shortDefinitionEs: "Sintesis informativa de precio, tecnico, fundamentos, noticias, riesgos y cobertura de datos.",
    category: "market",
    cautionEn: "It is not an investment recommendation.",
    cautionEs: "No es una recomendacion de inversion.",
  },
  marketSignal: {
    key: "marketSignal",
    labelEn: "Market signal",
    labelEs: "Senal de mercado",
    shortDefinitionEn: "Integrated score that combines available analytical layers into a non-advisory reading.",
    shortDefinitionEs: "Score integrado que combina capas analiticas disponibles en una lectura informativa.",
    category: "market",
  },
  dataConfidence: {
    key: "dataConfidence",
    labelEn: "Data confidence",
    labelEs: "Confianza de datos",
    shortDefinitionEn: "Qualitative indication of how complete and reliable the available data layers are.",
    shortDefinitionEs: "Indicacion cualitativa sobre completitud y confiabilidad de las capas de datos disponibles.",
    category: "risk",
  },
  newsPulse: {
    key: "newsPulse",
    labelEn: "News pulse",
    labelEs: "Pulso de noticias",
    shortDefinitionEn: "Short view of recent headlines used as context for the asset report.",
    shortDefinitionEs: "Vista breve de titulares recientes usados como contexto del reporte del activo.",
    category: "market",
  },
  riskSummary: {
    key: "riskSummary",
    labelEn: "Risk summary",
    labelEs: "Resumen de riesgos",
    shortDefinitionEn: "Compact list of the main risks and limitations relevant to the instrument.",
    shortDefinitionEs: "Lista compacta de riesgos y limitaciones principales del instrumento.",
    category: "risk",
  },
};

export function getGlossaryTerm(key: GlossaryTermKey) {
  return glossaryTerms[key];
}

export function getGlossaryTermsByCategory(category: GlossaryTerm["category"]) {
  return Object.values(glossaryTerms).filter((term) => term.category === category);
}
