export const localToAdrSymbol: Record<string, string> = {
  GGAL: "GGAL",
  YPFD: "YPF",
  PAMP: "PAM",
  TGSU2: "TGS",
  CEPU: "CEPU",
  EDN: "EDN",
  LOMA: "LOMA",
  BBAR: "BBAR",
  BMA: "BMA",
  SUPV: "SUPV",
  CRES: "CRESY",
  IRSA: "IRS",
  TECO2: "TEO",
};

export const adrToLocalSymbol: Record<string, string> = {
  GGAL: "GGAL",
  YPF: "YPFD",
  PAM: "PAMP",
  TGS: "TGSU2",
  CEPU: "CEPU",
  EDN: "EDN",
  LOMA: "LOMA",
  BBAR: "BBAR",
  BMA: "BMA",
  SUPV: "SUPV",
  CRESY: "CRES",
  IRS: "IRSA",
  TEO: "TECO2",
};
