export const cedearUnderlyingSymbols: Record<string, { underlyingSymbol: string; type: "stock" | "etf"; ratio?: number }> = {
  AAPL: { underlyingSymbol: "AAPL", type: "stock" },
  MSFT: { underlyingSymbol: "MSFT", type: "stock" },
  GOOGL: { underlyingSymbol: "GOOGL", type: "stock" },
  AMZN: { underlyingSymbol: "AMZN", type: "stock" },
  META: { underlyingSymbol: "META", type: "stock" },
  NVDA: { underlyingSymbol: "NVDA", type: "stock" },
  TSLA: { underlyingSymbol: "TSLA", type: "stock" },
  AMD: { underlyingSymbol: "AMD", type: "stock" },
  AVGO: { underlyingSymbol: "AVGO", type: "stock" },
  KO: { underlyingSymbol: "KO", type: "stock" },
  PEP: { underlyingSymbol: "PEP", type: "stock" },
  MCD: { underlyingSymbol: "MCD", type: "stock" },
  WMT: { underlyingSymbol: "WMT", type: "stock" },
  JPM: { underlyingSymbol: "JPM", type: "stock" },
  BAC: { underlyingSymbol: "BAC", type: "stock" },
  DIS: { underlyingSymbol: "DIS", type: "stock" },
  NFLX: { underlyingSymbol: "NFLX", type: "stock" },
  MELI: { underlyingSymbol: "MELI", type: "stock" },
  SPY: { underlyingSymbol: "SPY", type: "etf" },
  QQQ: { underlyingSymbol: "QQQ", type: "etf" },
  DIA: { underlyingSymbol: "DIA", type: "etf" },
  IWM: { underlyingSymbol: "IWM", type: "etf" },
  EWZ: { underlyingSymbol: "EWZ", type: "etf" },
  ARKK: { underlyingSymbol: "ARKK", type: "etf" },
  XLF: { underlyingSymbol: "XLF", type: "etf" },
  XLK: { underlyingSymbol: "XLK", type: "etf" },
  XLE: { underlyingSymbol: "XLE", type: "etf" },
};

export const cedearWarning = "El CEDEAR puede diferir del subyacente por CCL/MEP implicito, ratio, liquidez, moneda, plazo y spread.";
