export const cedearUnderlyingSymbols: Record<string, { underlyingSymbol: string; type: "stock" | "etf"; ratio?: number }> = {
  AAPL: { underlyingSymbol: "AAPL", type: "stock", ratio: 20 },
  MSFT: { underlyingSymbol: "MSFT", type: "stock", ratio: 30 },
  GOOGL: { underlyingSymbol: "GOOGL", type: "stock", ratio: 58 },
  AMZN: { underlyingSymbol: "AMZN", type: "stock", ratio: 144 },
  META: { underlyingSymbol: "META", type: "stock", ratio: 24 },
  NVDA: { underlyingSymbol: "NVDA", type: "stock", ratio: 24 },
  TSLA: { underlyingSymbol: "TSLA", type: "stock", ratio: 15 },
  AMD: { underlyingSymbol: "AMD", type: "stock", ratio: 10 },
  AVGO: { underlyingSymbol: "AVGO", type: "stock" },
  KO: { underlyingSymbol: "KO", type: "stock", ratio: 5 },
  PEP: { underlyingSymbol: "PEP", type: "stock", ratio: 18 },
  MCD: { underlyingSymbol: "MCD", type: "stock", ratio: 24 },
  WMT: { underlyingSymbol: "WMT", type: "stock", ratio: 30 },
  JPM: { underlyingSymbol: "JPM", type: "stock", ratio: 15 },
  BAC: { underlyingSymbol: "BAC", type: "stock", ratio: 4 },
  DIS: { underlyingSymbol: "DIS", type: "stock" },
  NFLX: { underlyingSymbol: "NFLX", type: "stock", ratio: 16 },
  MELI: { underlyingSymbol: "MELI", type: "stock", ratio: 120 },
  SPY: { underlyingSymbol: "SPY", type: "etf", ratio: 60 },
  QQQ: { underlyingSymbol: "QQQ", type: "etf", ratio: 20 },
  DIA: { underlyingSymbol: "DIA", type: "etf", ratio: 20 },
  IWM: { underlyingSymbol: "IWM", type: "etf", ratio: 10 },
  EWZ: { underlyingSymbol: "EWZ", type: "etf" },
  ARKK: { underlyingSymbol: "ARKK", type: "etf" },
  XLF: { underlyingSymbol: "XLF", type: "etf" },
  XLK: { underlyingSymbol: "XLK", type: "etf" },
  XLE: { underlyingSymbol: "XLE", type: "etf", ratio: 10 },
  INTC: { underlyingSymbol: "INTC", type: "stock", ratio: 5 },
  BABA: { underlyingSymbol: "BABA", type: "stock", ratio: 9 },
  COST: { underlyingSymbol: "COST", type: "stock", ratio: 48 },
  PG: { underlyingSymbol: "PG", type: "stock", ratio: 15 },
  JNJ: { underlyingSymbol: "JNJ", type: "stock", ratio: 15 },
  V: { underlyingSymbol: "V", type: "stock", ratio: 18 },
  MA: { underlyingSymbol: "MA", type: "stock", ratio: 33 },
  BRKB: { underlyingSymbol: "BRKB", type: "stock", ratio: 22 },
  GLD: { underlyingSymbol: "GLD", type: "etf", ratio: 10 },
  SLV: { underlyingSymbol: "SLV", type: "etf", ratio: 10 },
  XOM: { underlyingSymbol: "XOM", type: "stock", ratio: 10 },
  CVX: { underlyingSymbol: "CVX", type: "stock", ratio: 16 },
  VALE: { underlyingSymbol: "VALE", type: "stock", ratio: 2 },
  PBR: { underlyingSymbol: "PBR", type: "stock", ratio: 2 },
};

export function getCedearRatio(symbol: string) {
  return cedearUnderlyingSymbols[symbol.trim().toUpperCase()]?.ratio;
}

export const cedearWarning = "El CEDEAR puede diferir del subyacente por CCL/MEP implicito, ratio, liquidez, moneda, plazo y spread.";
