"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, BookOpen, ExternalLink } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { useLanguage } from "@/lib/i18n/useLanguage";
import { getDeliveredAlert, markAlertRead, type AlertEventRecord } from "@/lib/alerts/client";

export function AlertDetail({ id }: { id: string }) {
  const { language } = useLanguage();
  const [alert, setAlert] = useState<AlertEventRecord | null | undefined>();
  useEffect(() => { getDeliveredAlert(id).then((result) => { setAlert(result); if (result && !result.readAt) void markAlertRead(result.id); }).catch(() => setAlert(null)); }, [id]);
  const symbol = alert?.instrumentSymbol;
  return <AppShell>{alert === undefined ? <p className="cma-panel p-6 text-sm">{language === "es" ? "Cargando…" : "Loading…"}</p> : alert === null ? <div className="cma-panel p-7"><h1 className="text-2xl font-semibold">{language === "es" ? "Alerta no disponible" : "Alert unavailable"}</h1><Link href="/alerts" className="mt-5 inline-flex min-h-11 items-center gap-2 text-cyan-200"><ArrowLeft size={16} />{language === "es" ? "Volver" : "Back"}</Link></div> : <div className="space-y-5">
    <Link href="/alerts" className="inline-flex min-h-11 items-center gap-2 text-sm text-[var(--cma-text-secondary)]"><ArrowLeft size={16} />{language === "es" ? "Centro de alertas" : "Alert center"}</Link>
    <header className="cma-panel-elevated p-6"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--cma-accent-cyan)]">{alert.category.replaceAll("_", " ")}</p><h1 className="mt-2 text-3xl font-semibold text-[var(--cma-text-primary)]">{alert.localizedContent.title?.[language] ?? alert.title}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--cma-text-secondary)]">{alert.localizedContent.summary?.[language] ?? alert.summary}</p><div className="mt-5 flex flex-wrap gap-2 text-xs"><span className="rounded-full border border-[var(--cma-border-soft)] px-2 py-1">{alert.severity}</span><span className="rounded-full border border-[var(--cma-border-soft)] px-2 py-1">{language === "es" ? "Confianza técnica" : "Technical confidence"}: {Math.round(alert.confidenceScore * 100)}%</span><span className="rounded-full border border-[var(--cma-border-soft)] px-2 py-1">{alert.provider}</span><span className="rounded-full border border-[var(--cma-border-soft)] px-2 py-1">{alert.freshnessStatus}</span></div></header>
    <section className="cma-panel p-6"><h2 className="text-xl font-semibold text-[var(--cma-text-primary)]">{language === "es" ? "Datos observados" : "Observed data"}</h2><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{alert.evidence.map((item) => <div key={item.key} className="rounded-lg border border-[var(--cma-border-soft)] bg-[var(--cma-bg-elevated)] p-4"><dt className="text-xs text-[var(--cma-text-muted)]">{item.label}</dt><dd className="mt-1 font-semibold text-[var(--cma-text-primary)]">{item.value}{item.unit ? ` ${item.unit}` : ""}</dd><dd className="mt-2 text-[11px] text-[var(--cma-text-muted)]">{item.provider} · {new Date(item.observedAt).toLocaleString(language === "es" ? "es-AR" : "en-US")}</dd></div>)}</dl></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="cma-panel p-6"><h2 className="text-lg font-semibold">{language === "es" ? "Trazabilidad" : "Traceability"}</h2><dl className="mt-4 space-y-2 text-sm text-[var(--cma-text-secondary)]"><div><dt className="inline font-medium">Instrument: </dt><dd className="inline">{alert.instrumentSymbol} · {alert.market} · {alert.currency}</dd></div><div><dt className="inline font-medium">Rule: </dt><dd className="inline">{alert.ruleId} v{alert.ruleVersion}</dd></div><div><dt className="inline font-medium">Observed: </dt><dd className="inline">{new Date(alert.observedAt).toLocaleString()}</dd></div><div><dt className="inline font-medium">Fetched: </dt><dd className="inline">{new Date(alert.fetchedAt).toLocaleString()}</dd></div></dl></div><div className="cma-panel p-6"><h2 className="text-lg font-semibold">{language === "es" ? "Limitaciones" : "Limitations"}</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-[var(--cma-text-secondary)]">{alert.limitations.map((item) => <li key={item}>{item}</li>)}</ul></div></section>
    <div className="flex flex-wrap gap-3"><Link href={`/trade-radar?symbol=${encodeURIComponent(String(symbol ?? ""))}&instrumentId=${encodeURIComponent(alert.instrumentId)}&interval=1d&analyze=1`} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-cyan-300/30 bg-cyan-300/10 px-4 text-sm font-semibold text-cyan-100">{language === "es" ? "Abrir en Trade Radar" : "Open in Trade Radar"}<ExternalLink size={15} /></Link><Link href="/alerts/guide" className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[var(--cma-border-soft)] px-4 text-sm text-[var(--cma-text-secondary)]"><BookOpen size={15} />{language === "es" ? "Entender esta alerta" : "Understand this alert"}</Link></div>
    <p className="text-xs text-[var(--cma-text-muted)]">{language === "es" ? "Análisis informativo. No constituye asesoramiento financiero personalizado ni una orden." : "Informational analysis. It is not personalized financial advice or an order."}</p>
  </div>}</AppShell>;
}
