import type { FixedIncomeInstrument } from "./types";

const sharedSovereignTerms = {
  issuer: "Argentine Treasury",
  couponType: "fixed" as const,
  amortizationType: "bullet" as const,
  faceValue: 100,
  couponFrequency: 2,
  issueDate: "2020-09-04",
  maturityDate: "2030-07-09",
  yearsToMaturity: 4.2,
  accruedInterest: 0,
  sourceLabel: "Mock fixed income data",
  isMock: true,
};

const mockFixedIncomeInstruments: FixedIncomeInstrument[] = [
  {
    symbol: "AL30",
    underlyingSymbol: "AL30",
    tradingSymbol: "AL30",
    speciesType: "peso",
    tradingCurrency: "ARS",
    settlementCurrency: "ARS",
    displayCurrency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "pesos",
    indexationType: "none",
    marketDisplayPrice: 58400,
    analyticalPrice: 58.4,
    marketConventionLabel: "Peso trading species",
    marketConventionLabelEn: "Peso trading species",
    marketConventionLabelEs: "Especie en pesos",
    name: "Bonar 2030",
    type: "sovereign_bond",
    currency: "ARS",
    law: "argentina",
    // Precio visible local simulado separado del precio analítico normalizado usado para métricas de renta fija.
    marketPrice: 58.4,
    annualCouponRate: 0.0075,
    ...sharedSovereignTerms,
  },
  {
    symbol: "AL30D",
    underlyingSymbol: "AL30",
    tradingSymbol: "AL30D",
    speciesType: "dollar_mep",
    tradingCurrency: "USD",
    settlementCurrency: "USD",
    displayCurrency: "USD",
    quoteCurrency: "USD",
    settlementContext: "dollar_mep",
    indexationType: "none",
    marketDisplayPrice: 58.4,
    analyticalPrice: 58.4,
    marketConventionLabel: "Dollar MEP species",
    marketConventionLabelEn: "Dollar MEP species",
    marketConventionLabelEs: "Especie dólar MEP",
    name: "Bonar 2030 - Dollar MEP species",
    type: "sovereign_bond",
    currency: "USD",
    law: "argentina",
    marketPrice: 58.4,
    annualCouponRate: 0.0075,
    ...sharedSovereignTerms,
  },
  {
    symbol: "AL30C",
    underlyingSymbol: "AL30",
    tradingSymbol: "AL30C",
    speciesType: "dollar_cable",
    tradingCurrency: "USD",
    settlementCurrency: "USD",
    displayCurrency: "USD",
    quoteCurrency: "USD",
    settlementContext: "dollar_cable",
    indexationType: "none",
    marketDisplayPrice: 57.9,
    analyticalPrice: 57.9,
    marketConventionLabel: "Dollar cable/CCL species",
    marketConventionLabelEn: "Dollar cable/CCL species",
    marketConventionLabelEs: "Especie dólar cable/CCL",
    name: "Bonar 2030 - Dollar cable/CCL species",
    type: "sovereign_bond",
    currency: "USD",
    law: "argentina",
    marketPrice: 57.9,
    annualCouponRate: 0.0075,
    ...sharedSovereignTerms,
  },
  {
    symbol: "GD30",
    underlyingSymbol: "GD30",
    tradingSymbol: "GD30",
    speciesType: "peso",
    tradingCurrency: "ARS",
    settlementCurrency: "ARS",
    displayCurrency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "pesos",
    indexationType: "none",
    marketDisplayPrice: 92300,
    analyticalPrice: 61.7,
    marketConventionLabel: "Peso trading species",
    marketConventionLabelEn: "Peso trading species",
    marketConventionLabelEs: "Especie en pesos",
    name: "Global 2030",
    type: "global_bond",
    currency: "ARS",
    law: "new_york",
    // Precio visible local simulado separado del precio analítico normalizado usado para métricas de renta fija.
    marketPrice: 61.7,
    annualCouponRate: 0.005,
    ...sharedSovereignTerms,
  },
  {
    symbol: "GD30D",
    underlyingSymbol: "GD30",
    tradingSymbol: "GD30D",
    speciesType: "dollar_mep",
    tradingCurrency: "USD",
    settlementCurrency: "USD",
    displayCurrency: "USD",
    quoteCurrency: "USD",
    settlementContext: "dollar_mep",
    indexationType: "none",
    marketDisplayPrice: 61.7,
    analyticalPrice: 61.7,
    marketConventionLabel: "Dollar MEP species",
    marketConventionLabelEn: "Dollar MEP species",
    marketConventionLabelEs: "Especie dólar MEP",
    name: "Global 2030 - Dollar MEP species",
    type: "global_bond",
    currency: "USD",
    law: "new_york",
    marketPrice: 61.7,
    annualCouponRate: 0.005,
    ...sharedSovereignTerms,
  },
  {
    symbol: "GD30C",
    underlyingSymbol: "GD30",
    tradingSymbol: "GD30C",
    speciesType: "dollar_cable",
    tradingCurrency: "USD",
    settlementCurrency: "USD",
    displayCurrency: "USD",
    quoteCurrency: "USD",
    settlementContext: "dollar_cable",
    indexationType: "none",
    marketDisplayPrice: 61.2,
    analyticalPrice: 61.2,
    marketConventionLabel: "Dollar cable/CCL species",
    marketConventionLabelEn: "Dollar cable/CCL species",
    marketConventionLabelEs: "Especie dólar cable/CCL",
    name: "Global 2030 - Dollar cable/CCL species",
    type: "global_bond",
    currency: "USD",
    law: "new_york",
    marketPrice: 61.2,
    annualCouponRate: 0.005,
    ...sharedSovereignTerms,
  },
  {
    symbol: "TX26",
    underlyingSymbol: "TX26",
    tradingSymbol: "TX26",
    speciesType: "cer",
    tradingCurrency: "ARS",
    settlementCurrency: "ARS",
    displayCurrency: "ARS",
    quoteCurrency: "ARS",
    settlementContext: "cer_linked",
    indexationType: "CER",
    marketDisplayPrice: 142.8,
    analyticalPrice: 142.8,
    marketConventionLabel: "CER-linked ARS bond",
    marketConventionLabelEn: "CER-linked ARS bond",
    marketConventionLabelEs: "Bono CER",
    name: "CER-linked Argentine Treasury bond",
    type: "cer_bond",
    issuer: "Argentine Treasury",
    currency: "ARS",
    law: "argentina",
    amortizationType: "bullet",
    couponType: "cer_adjusted",
    faceValue: 100,
    marketPrice: 142.8,
    annualCouponRate: 0.0145,
    couponFrequency: 2,
    issueDate: "2021-11-09",
    maturityDate: "2026-11-09",
    yearsToMaturity: 0.5,
    accruedInterest: 0,
    cerCoefficient: 1.42,
    sourceLabel: "Mock fixed income data",
    isMock: true,
  },
];

export function getMockFixedIncomeInstrument(symbol: string) {
  const normalizedSymbol = symbol.trim().toUpperCase();
  return mockFixedIncomeInstruments.find((instrument) => instrument.symbol === normalizedSymbol) ?? null;
}

export function getAllMockFixedIncomeInstruments() {
  return [...mockFixedIncomeInstruments];
}
