import type { ArgentinaInstrument } from "./types";

function equity(symbol: string, name: string): ArgentinaInstrument {
  return {
    symbol,
    displaySymbol: symbol,
    name,
    type: "equity",
    market: "BYMA",
    currency: "ARS",
    quoteCurrency: "ARS",
    sourceStatus: "mock",
  };
}

function bond(input: Omit<ArgentinaInstrument, "market" | "currency" | "sourceStatus"> & { currency?: string }): ArgentinaInstrument {
  return {
    ...input,
    market: "BYMA",
    currency: input.currency ?? input.quoteCurrency,
    sourceStatus: "mock",
  };
}

function cedear(symbol: string, name: string, ratio: number): ArgentinaInstrument {
  return {
    symbol,
    displaySymbol: `${symbol} CEDEAR`,
    localSymbol: symbol,
    name,
    type: "cedear",
    localInstrumentType: "cedear",
    market: "BYMA",
    currency: "ARS",
    quoteCurrency: "ARS",
    underlyingSymbol: symbol,
    cedearRatio: ratio,
    sourceStatus: "mock",
    context: "BYMA CEDEAR",
  };
}

export const argentinaInstrumentRegistry: ArgentinaInstrument[] = [
  equity("GGAL", "Grupo Financiero Galicia"),
  equity("YPFD", "YPF Sociedad Anonima"),
  equity("PAMP", "Pampa Energia"),
  equity("TXAR", "Ternium Argentina"),
  equity("ALUA", "Aluar Aluminio Argentino"),
  equity("TGSU2", "Transportadora de Gas del Sur"),
  equity("CEPU", "Central Puerto"),
  equity("COME", "Sociedad Comercial del Plata"),
  equity("BYMA", "Bolsas y Mercados Argentinos"),
  equity("SUPV", "Grupo Supervielle"),
  equity("VALO", "Grupo Financiero Valores"),
  equity("BBAR", "Banco BBVA Argentina"),
  equity("BMA", "Banco Macro"),
  equity("EDN", "Edenor"),
  equity("TRAN", "Transener"),
  equity("TGNO4", "Transportadora de Gas del Norte"),
  equity("MIRG", "Mirgor"),
  equity("LOMA", "Loma Negra"),
  equity("CRES", "Cresud"),
  equity("IRSA", "IRSA"),
  equity("METR", "Metrogas"),
  equity("AGRO", "Agrometal"),
  equity("HARG", "Holcim Argentina"),
  equity("TECO2", "Telecom Argentina"),
  equity("MOLI", "Molinos Rio de la Plata"),
  bond({
    symbol: "AL30",
    displaySymbol: "AL30",
    name: "Bonar 2030",
    type: "sovereign_bond",
    quoteCurrency: "ARS",
    speciesType: "peso_species",
    underlyingSymbol: "AL30",
    maturityDate: "2030-07-09",
    law: "Local law",
  }),
  bond({
    symbol: "AL30D",
    displaySymbol: "AL30D",
    name: "Bonar 2030 - Dollar MEP species",
    type: "sovereign_bond",
    quoteCurrency: "USD",
    speciesType: "dollar_mep_species",
    underlyingSymbol: "AL30",
    maturityDate: "2030-07-09",
    law: "Local law",
  }),
  bond({
    symbol: "AL30C",
    displaySymbol: "AL30C",
    name: "Bonar 2030 - Dollar cable/CCL species",
    type: "sovereign_bond",
    quoteCurrency: "USD",
    speciesType: "dollar_cable_species",
    underlyingSymbol: "AL30",
    maturityDate: "2030-07-09",
    law: "Local law",
  }),
  bond({
    symbol: "GD30",
    displaySymbol: "GD30",
    name: "Global 2030",
    type: "sovereign_bond",
    quoteCurrency: "ARS",
    speciesType: "peso_species",
    underlyingSymbol: "GD30",
    maturityDate: "2030-07-09",
    law: "New York law",
  }),
  bond({
    symbol: "GD30D",
    displaySymbol: "GD30D",
    name: "Global 2030 - Dollar MEP species",
    type: "sovereign_bond",
    quoteCurrency: "USD",
    speciesType: "dollar_mep_species",
    underlyingSymbol: "GD30",
    maturityDate: "2030-07-09",
    law: "New York law",
  }),
  bond({
    symbol: "GD30C",
    displaySymbol: "GD30C",
    name: "Global 2030 - Dollar cable/CCL species",
    type: "sovereign_bond",
    quoteCurrency: "USD",
    speciesType: "dollar_cable_species",
    underlyingSymbol: "GD30",
    maturityDate: "2030-07-09",
    law: "New York law",
  }),
  bond({
    symbol: "TX26",
    displaySymbol: "TX26",
    name: "CER-linked Argentine Treasury bond",
    type: "treasury_bill",
    quoteCurrency: "ARS",
    underlyingSymbol: "TX26",
    maturityDate: "2026-11-09",
    indexation: "CER",
    law: "Local law",
  }),
  bond({
    symbol: "S31Y6",
    displaySymbol: "S31Y6",
    name: "Sample Lecap",
    type: "lecaps",
    quoteCurrency: "ARS",
    underlyingSymbol: "S31Y6",
    maturityDate: "2026-05-31",
    law: "Local law",
  }),
  bond({
    symbol: "AE38",
    displaySymbol: "AE38",
    name: "Bonar 2038",
    type: "sovereign_bond",
    quoteCurrency: "ARS",
    speciesType: "peso_species",
    underlyingSymbol: "AE38",
    maturityDate: "2038-01-09",
    law: "Local law",
  }),
  bond({
    symbol: "AE38D",
    displaySymbol: "AE38D",
    name: "Bonar 2038 - Dollar MEP species",
    type: "sovereign_bond",
    quoteCurrency: "USD",
    speciesType: "dollar_mep_species",
    underlyingSymbol: "AE38",
    maturityDate: "2038-01-09",
    law: "Local law",
  }),
  bond({
    symbol: "GD35",
    displaySymbol: "GD35",
    name: "Global 2035",
    type: "sovereign_bond",
    quoteCurrency: "ARS",
    speciesType: "peso_species",
    underlyingSymbol: "GD35",
    maturityDate: "2035-07-09",
    law: "New York law",
  }),
  bond({
    symbol: "GD35D",
    displaySymbol: "GD35D",
    name: "Global 2035 - Dollar MEP species",
    type: "sovereign_bond",
    quoteCurrency: "USD",
    speciesType: "dollar_mep_species",
    underlyingSymbol: "GD35",
    maturityDate: "2035-07-09",
    law: "New York law",
  }),
  bond({
    symbol: "GD38",
    displaySymbol: "GD38",
    name: "Global 2038",
    type: "sovereign_bond",
    quoteCurrency: "ARS",
    speciesType: "peso_species",
    underlyingSymbol: "GD38",
    maturityDate: "2038-01-09",
    law: "New York law",
  }),
  bond({
    symbol: "GD38D",
    displaySymbol: "GD38D",
    name: "Global 2038 - Dollar MEP species",
    type: "sovereign_bond",
    quoteCurrency: "USD",
    speciesType: "dollar_mep_species",
    underlyingSymbol: "GD38",
    maturityDate: "2038-01-09",
    law: "New York law",
  }),
  bond({
    symbol: "AL35",
    displaySymbol: "AL35",
    name: "Bonar 2035",
    type: "sovereign_bond",
    quoteCurrency: "ARS",
    speciesType: "peso_species",
    underlyingSymbol: "AL35",
    maturityDate: "2035-07-09",
    law: "Local law",
  }),
  bond({
    symbol: "AL35D",
    displaySymbol: "AL35D",
    name: "Bonar 2035 - Dollar MEP species",
    type: "sovereign_bond",
    quoteCurrency: "USD",
    speciesType: "dollar_mep_species",
    underlyingSymbol: "AL35",
    maturityDate: "2035-07-09",
    law: "Local law",
  }),
  bond({
    symbol: "TZX26",
    displaySymbol: "TZX26",
    name: "CER-linked Treasury bond TZX26",
    type: "treasury_bill",
    quoteCurrency: "ARS",
    underlyingSymbol: "TZX26",
    maturityDate: "2026-06-30",
    indexation: "CER",
    law: "Local law",
  }),
  bond({
    symbol: "DICP",
    displaySymbol: "DICP",
    name: "Discount bond in pesos",
    type: "sovereign_bond",
    quoteCurrency: "ARS",
    underlyingSymbol: "DICP",
    indexation: "CER",
    law: "Local law",
  }),
  bond({
    symbol: "PARP",
    displaySymbol: "PARP",
    name: "Par bond in pesos",
    type: "sovereign_bond",
    quoteCurrency: "ARS",
    underlyingSymbol: "PARP",
    indexation: "CER",
    law: "Local law",
  }),
  cedear("AAPL", "Apple CEDEAR", 10),
  cedear("MSFT", "Microsoft CEDEAR", 5),
  cedear("NVDA", "NVIDIA CEDEAR", 24),
  cedear("TSLA", "Tesla CEDEAR", 15),
  cedear("AMZN", "Amazon CEDEAR", 72),
  cedear("META", "Meta CEDEAR", 8),
  cedear("GOOGL", "Alphabet CEDEAR", 58),
  cedear("AMD", "AMD CEDEAR", 10),
  cedear("INTC", "Intel CEDEAR", 5),
  cedear("NFLX", "Netflix CEDEAR", 16),
  cedear("MELI", "MercadoLibre CEDEAR", 60),
  cedear("BABA", "Alibaba CEDEAR", 9),
  cedear("KO", "Coca-Cola CEDEAR", 5),
  cedear("PEP", "PepsiCo CEDEAR", 18),
  cedear("MCD", "McDonald's CEDEAR", 24),
  cedear("WMT", "Walmart CEDEAR", 30),
  cedear("COST", "Costco CEDEAR", 48),
  cedear("PG", "Procter & Gamble CEDEAR", 15),
  cedear("JNJ", "Johnson & Johnson CEDEAR", 15),
  cedear("JPM", "JPMorgan Chase CEDEAR", 15),
  cedear("BAC", "Bank of America CEDEAR", 4),
  cedear("V", "Visa CEDEAR", 18),
  cedear("MA", "Mastercard CEDEAR", 33),
  cedear("BRKB", "Berkshire Hathaway CEDEAR", 22),
  cedear("SPY", "SPY CEDEAR", 20),
  cedear("QQQ", "QQQ CEDEAR", 20),
  cedear("DIA", "DIA CEDEAR", 20),
  cedear("IWM", "IWM CEDEAR", 20),
  cedear("XLE", "XLE CEDEAR", 10),
  cedear("GLD", "GLD CEDEAR", 10),
  cedear("SLV", "SLV CEDEAR", 10),
  cedear("XOM", "Exxon Mobil CEDEAR", 10),
  cedear("CVX", "Chevron CEDEAR", 16),
  cedear("VALE", "Vale CEDEAR", 2),
  cedear("PBR", "Petrobras CEDEAR", 2),
];

export function getArgentinaInstrumentFromRegistry(symbol: string) {
  const normalized = symbol.trim().toUpperCase();
  return argentinaInstrumentRegistry.find((instrument) => instrument.symbol === normalized) ?? null;
}

export function isArgentinaInstrument(symbol: string) {
  return Boolean(getArgentinaInstrumentFromRegistry(symbol));
}
