export const providerEquitySymbols = [
  "A3", "AGRO", "ALUA", "AUSO", "BBAR", "BHIP", "BMA", "BOLT", "BPAT", "BYMA",
  "CADO", "CAPX", "CARC", "CECO2", "CELU", "CEPU", "CGPA2", "COME", "CRES", "CTIO",
  "CVH", "DGCU2", "DOME", "ECOG", "EDN", "EDSH", "FERR", "FIPL", "GAMI", "GARO",
  "GBAN", "GCDI", "GCLA", "GGAL", "GRIM", "HARG", "HAVA", "HSAT", "IEB", "INAG",
  "INTR", "INVJ", "IRSA", "LEDE", "LOMA", "LONG", "METR", "MIRG", "MOLA", "MOLI",
  "MORI", "OEST", "PAMP", "PATA", "POLL", "RAGH", "REGE", "REIT", "RICH", "RIGO",
  "ROSE", "SAMI", "SEMI", "SUPV", "TECO2", "TECOD", "TGN4D", "TGNO4", "TGSU2",
  "TGSUD", "TRAN", "TXAR", "VALO", "YPFD",
] as const;

export const providerCedearSymbols = [
  "AAL", "AAP", "AAPL", "ABBV", "ABEV", "ABEV3", "ABNB", "ABT", "ACN", "ACWI",
  "ADBE", "ADGO", "ADI", "ADP", "ADS", "AEG", "AEM", "AI", "AIG", "AKOBD",
  "ALAB", "ALAD", "AMAT", "AMD", "AMGN", "AMX", "AMZN", "ANET", "ANF", "ARCO",
  "ARKK", "ARM", "ASML", "ASR", "ASTS", "AVGO", "AVY", "AXIA", "AXP", "AZN",
  "B", "BA", "BABA", "BAK", "BB", "BBAS3", "BBDC3", "BBV", "BCS", "BHP",
  "BIDU", "BIIB", "BIOX", "BKNG", "BKR", "BMNR", "BMY", "BNG", "BNY", "BP",
  "BPA11", "BRKB", "BSBR", "BX", "C", "CAAP", "CAH", "CAR", "CAT", "CC",
  "CCJ", "CCL", "CDE", "CEG", "CIBR", "CL", "CLS", "COIN", "COP", "COPX",
  "COST", "CRM", "CRWD", "CRWV", "CSCO", "CSNA3", "CVS", "CVX", "CX", "DAL",
  "DD", "DE", "DECK", "DEO", "DHR", "DIA", "DISN", "DOCU", "DOW", "E",
  "EA", "EBAY", "EC", "ECL", "EEM", "EFA", "EFX", "ELPC", "EMBJ", "EQNR",
  "ERIC", "ESGU", "ETHA", "ETSY", "EWJ", "EWY", "EWZ", "F", "FC", "FCX",
  "FD", "FDX", "FISV", "FMX", "FNMA", "FSLR", "FXI", "GDX", "GE", "GFI",
  "GGB", "GILD", "GLD", "GLNG", "GLOB", "GLW", "GM", "GOGLC", "GOGLD", "GOOGL",
  "GPRK", "GRMN", "GS", "GSK", "GT", "HAL", "HAPV3", "HD", "HDB", "HIMS",
  "HL", "HMC", "HMY", "HOG", "HON", "HOOD", "HPQ", "HSBC", "HSY", "HUT",
  "HWM", "IBB", "IBIT", "IBM", "IBN", "ICLN", "IEMG", "IEUR", "IFF", "IJH",
  "ILF", "INFY", "ING", "INTC", "IP", "IREN", "ISRG", "ITA", "ITUB", "ITUB3",
  "IVE", "IVV", "IVW", "IWM", "JCI", "JD", "JMIA", "JNJ", "JOYY", "JPM",
  "KB", "KEEL", "KEP", "KGC", "KMB", "KO", "KOFM", "LAC", "LAR", "LLY",
  "LMT", "LND", "LRCX", "LREN3", "LVS", "LYG", "MA", "MCD", "MDLZ", "MDT",
  "MELI", "META", "MFG", "MGLU3", "MMM", "MO", "MOS", "MP", "MRK", "MRNA",
  "MRSH", "MRVL", "MSFT", "MSI", "MSTR", "MU", "MUFG", "MUX", "NAT3D", "NATU3",
  "NBIS", "NEE", "NEM", "NFLX", "NG", "NGG", "NIO", "NKE", "NMR", "NOKA",
  "NOW", "NTES", "NU", "NUE", "NVDA", "NVO", "NVS", "NXE", "O", "OC",
  "OD", "OKLO", "ONDS", "ORCL", "ORLY", "OXY", "PAAS", "PAC", "PAGS", "PANW",
  "PATH", "PBI", "PBR", "PCAR", "PDD", "PEP", "PETR3", "PETRD", "PFE", "PG",
  "PHG", "PINS", "PKS", "PLTR", "PM", "PRIO3", "PSQ", "PSX", "PYPL", "QCOM",
  "QQQ", "RACE", "RBLX", "RENT3", "RGTI", "RIO", "RIOT", "RKLB", "ROKU", "ROST",
  "RSP", "RTX", "SAN", "SAP", "SATL", "SBS", "SBSP3", "SBUX", "SCCO", "SCHW",
  "SDA", "SE", "SH", "SHEL", "SHOP", "SID", "SLB", "SLV", "SMH", "SMSN",
  "SNA", "SNAP", "SNDK", "SNOW", "SONY", "SPCE", "SPCX", "SPGI", "SPHQ", "SPOT",
  "SPXL", "SPY", "STLA", "STNE", "SUZ", "SUZB3", "SWKS", "SYY", "T", "TC",
  "TCOM", "TD", "TEAM", "TEM", "TEN", "TGT", "TIMB", "TIMS3", "TJX", "TM",
  "TMO", "TMUS", "TQQQ", "TRIP", "TRVV", "TSLA", "TSM", "TTE", "TV", "TWLO",
  "TXN", "TXR", "UAL", "UBER", "UGP", "UL", "UNH", "UNP", "UPST", "URA",
  "URBN", "USB", "USO", "V", "VAL3D", "VALE", "VALE3", "VC", "VD", "VEA",
  "VIG", "VIST", "VIV", "VIVT3", "VOD", "VRSN", "VRTX", "VST", "VXX", "VZ",
  "WBO", "WEGE3", "WFC", "WMT", "XLB", "XLC", "XLE", "XLF", "XLI", "XLK",
  "XLP", "XLRE", "XLU", "XLV", "XLY", "XME", "XOM", "XP", "XPEV", "XROX",
  "XYZ", "YELP", "ZM",
] as const;

export const providerInstrumentNames: Record<string, string> = {
  A3: "A3 Mercados",
  AGRO: "Agrometal",
  ALUA: "Aluar Aluminio Argentino",
  AUSO: "Autopistas del Sol",
  BBAR: "Banco BBVA Argentina",
  BHIP: "Banco Hipotecario",
  BMA: "Banco Macro",
  BOLT: "Boldt",
  BPAT: "Banco Patagonia",
  BYMA: "Bolsas y Mercados Argentinos",
  CADO: "Carlos Casado",
  CAPX: "Capex",
  CARC: "Carboclor",
  CECO2: "Central Costanera",
  CELU: "Celulosa Argentina",
  CEPU: "Central Puerto",
  CGPA2: "Camuzzi Gas Pampeana",
  COME: "Sociedad Comercial del Plata",
  CRES: "Cresud",
  CTIO: "Consultatio",
  CVH: "Cablevision Holding",
  DGCU2: "Distribuidora de Gas Cuyana",
  DOME: "Domec",
  ECOG: "ECOGAS Inversiones",
  EDN: "Edenor",
  EDSH: "Empresa Distribuidora de Electricidad de Salta",
  FERR: "Ferrum",
  FIPL: "Fiplasto",
  GAMI: "Garovaglio y Zorraquin",
  GARO: "Garovaglio y Zorraquin",
  GBAN: "Gas Natural BAN",
  GCDI: "GCDI",
  GCLA: "Grupo Clarin",
  GGAL: "Grupo Financiero Galicia",
  GRIM: "Grimoldi",
  HARG: "Holcim Argentina",
  HAVA: "Havanna Holding",
  HSAT: "Holdsat",
  IEB: "IEB Construcciones",
  INAG: "Insumos Agroquimicos",
  INTR: "Introductora de Buenos Aires",
  INVJ: "Inversora Juramento",
  IRSA: "IRSA Inversiones y Representaciones",
  LEDE: "Ledesma",
  LOMA: "Loma Negra",
  LONG: "Longvie",
  METR: "Metrogas",
  MIRG: "Mirgor",
  MOLA: "Molinos Agro",
  MOLI: "Molinos Rio de la Plata",
  MORI: "Morixe",
  OEST: "Grupo Concesionario del Oeste",
  PAMP: "Pampa Energia",
  PATA: "Importadora y Exportadora de la Patagonia",
  POLL: "Polledo",
  RAGH: "Raghsa",
  REGE: "Garcia Reguera",
  REIT: "FCI Cerrado Inmobiliario REIT Ciclo Nova",
  RICH: "Laboratorios Richmond",
  RIGO: "Rigolleau",
  ROSE: "Rosenbusch",
  SAMI: "San Miguel",
  SEMI: "Molinos Juan Semino",
  SUPV: "Grupo Supervielle",
  TECO2: "Telecom Argentina",
  TECOD: "Telecom Argentina",
  TGN4D: "Transportadora de Gas del Norte",
  TGNO4: "Transportadora de Gas del Norte",
  TGSU2: "Transportadora de Gas del Sur",
  TGSUD: "Transportadora de Gas del Sur",
  TRAN: "Transener",
  TXAR: "Ternium Argentina",
  VALO: "Grupo Financiero Valores",
  YPFD: "YPF",
  AAPL: "Apple Inc.",
  MSFT: "Microsoft Corporation",
  GOOGL: "Alphabet Inc.",
  AMZN: "Amazon.com Inc.",
  META: "Meta Platforms Inc.",
  NVDA: "NVIDIA Corporation",
  TSLA: "Tesla Inc.",
  AMD: "Advanced Micro Devices Inc.",
  INTC: "Intel Corporation",
  NFLX: "Netflix Inc.",
  MELI: "MercadoLibre Inc.",
  KO: "The Coca-Cola Company",
  PEP: "PepsiCo Inc.",
  MCD: "McDonald's Corporation",
  WMT: "Walmart Inc.",
  COST: "Costco Wholesale Corporation",
  PG: "Procter & Gamble Company",
  JNJ: "Johnson & Johnson",
  JPM: "JPMorgan Chase & Co.",
  BAC: "Bank of America Corporation",
  V: "Visa Inc.",
  MA: "Mastercard Incorporated",
  BRKB: "Berkshire Hathaway Inc.",
  SPY: "SPDR S&P 500 ETF Trust",
  QQQ: "Invesco QQQ Trust",
  DIA: "SPDR Dow Jones Industrial Average ETF",
  IWM: "iShares Russell 2000 ETF",
  XLE: "Energy Select Sector SPDR Fund",
  GLD: "SPDR Gold Shares",
  SLV: "iShares Silver Trust",
  XOM: "Exxon Mobil Corporation",
  CVX: "Chevron Corporation",
  VALE: "Vale S.A.",
  PBR: "Petroleo Brasileiro S.A.",
};

