export const assetLogoDomains: Record<string, string> = {
  AAPL: "apple.com",
  TSLA: "tesla.com",
  MSFT: "microsoft.com",
  AMZN: "amazon.com",
  GOOGL: "abc.xyz",
  GOOG: "google.com",
  META: "meta.com",
  NVDA: "nvidia.com",
  KO: "coca-cola.com",
  PEP: "pepsico.com",
  MCD: "mcdonalds.com",
  WMT: "walmart.com",
  COST: "costco.com",
  JPM: "jpmorganchase.com",
  BAC: "bankofamerica.com",
  V: "visa.com",
  MA: "mastercard.com",
  XOM: "exxonmobil.com",
  CVX: "chevron.com",
  MELI: "mercadolibre.com",
  NFLX: "netflix.com",
  AMD: "amd.com",
  INTC: "intel.com",
  SPY: "ssga.com",
  DIA: "ssga.com",
  QQQ: "invesco.com",
  IWM: "ishares.com",
  GLD: "spdrgoldshares.com",
  SLV: "ishares.com",
};

export const cryptoLogoIds: Record<string, string> = {
  "BTC-USD": "bitcoin",
  "ETH-USD": "ethereum",
  "SOL-USD": "solana",
  "BNB-USD": "bnb",
  "XRP-USD": "xrp",
  "ADA-USD": "cardano",
  "DOGE-USD": "dogecoin",
  "AVAX-USD": "avalanche",
  "LINK-USD": "chainlink",
  "DOT-USD": "polkadot",
};
